/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.importer.data.struct;

/**
 * Interface for {@link #TEST_STRUCT_ALL_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceTemplateGenerator}
 */
public interface TestStructAll extends test.com.top_logic.importer.data.struct.impl.TestStructAllBase {

	// Wrapper functionality.

}
