/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.element.structured.model.impl;

/**
 * Basic interface for {@link #A_NODE_CHILD_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ANodeChildBase extends test.com.top_logic.element.structured.model.CommonNode {

	/**
	 * Name of type <code>ANodeChild</code>
	 */
	String A_NODE_CHILD_TYPE = "ANodeChild";

}
