/*
 * SPDX-FileCopyrightText: 2023 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.element.structured.model.impl;

/**
 * Basic interface for {@link #A_NODE_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ANodeBase extends test.com.top_logic.element.structured.model.A, test.com.top_logic.element.structured.model.ANodeChild, test.com.top_logic.element.structured.model.BNodeChild {

	/**
	 * Name of type <code>ANode</code>
	 */
	String A_NODE_TYPE = "ANode";

	/**
	 * Part <code>name</code> of <code>ANode</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Getter for part {@link #AS1_ATTR}.
	 */
	@Override
	default String getAs1() {
		return (String) tValueByName(AS1_ATTR);
	}

	/**
	 * Getter for part {@link #CHILDREN_ATTR}.
	 */
	@Override
	@SuppressWarnings("unchecked")
	default java.util.List<? extends test.com.top_logic.element.structured.model.ANodeChild> getChildren() {
		return (java.util.List<? extends test.com.top_logic.element.structured.model.ANodeChild>) tValueByName(CHILDREN_ATTR);
	}

}
