/*
 * SPDX-FileCopyrightText: 2023 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.element.structured.model.impl;

import com.top_logic.knowledge.objects.KnowledgeObject;

/**
 * Wrapper implementation class for <code>TestTypes:CNode</code> business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.ImplementationTemplateGenerator}
 */
public class CNodeImpl extends com.top_logic.element.structured.wrap.AttributedStructuredElementWrapper implements test.com.top_logic.element.structured.model.CNode {

	/**
	 * Default constructor.
	 */
	public CNodeImpl(KnowledgeObject ko) {
		super(ko);
	}

}
