/*
 * SPDX-FileCopyrightText: 2019 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.demo.model.aspect;

import com.top_logic.demo.model.aspect.wrap.CNodeDefaultsBase;

/**
 * Interface for {@link #C_NODE_DEFAULTS_TYPE} business objects.
 * 
 * @author Automatically generated by
 *         {@link com.top_logic.element.model.generate.InterfaceTemplateGenerator}
 */
public interface CNodeDefaults extends CNodeDefaultsBase {

	// Wrapper functionality.

}
