/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.demo.model.dnd.wrap;

/**
 * Basic interface for {@link #LIBRARY_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface LibraryBase extends com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>Library</code>
	 */
	String LIBRARY_TYPE = "Library";

	/**
	 * Part <code>elements</code> of <code>Library</code>
	 * 
	 * <p>
	 * Declared as <code>test.dnd:NamedPlanElement</code> in configuration.
	 * </p>
	 */
	String ELEMENTS_ATTR = "elements";

	/**
	 * Part <code>name</code> of <code>Library</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Getter for part {@link #ELEMENTS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.demo.model.dnd.NamedPlanElement> getElements() {
		return (java.util.Set<? extends com.top_logic.demo.model.dnd.NamedPlanElement>) tValueByName(ELEMENTS_ATTR);
	}

	/**
	 * Live view of the {@link #ELEMENTS_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<com.top_logic.demo.model.dnd.NamedPlanElement> getElementsModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(ELEMENTS_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<com.top_logic.demo.model.dnd.NamedPlanElement> result = (java.util.Set<com.top_logic.demo.model.dnd.NamedPlanElement>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #ELEMENTS_ATTR}.
	 */
	default void setElements(java.util.Set<com.top_logic.demo.model.dnd.NamedPlanElement> newValue) {
		tUpdateByName(ELEMENTS_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #ELEMENTS_ATTR} reference.
	 */
	default void addElement(com.top_logic.demo.model.dnd.NamedPlanElement newValue) {
		tAddByName(ELEMENTS_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #ELEMENTS_ATTR} reference.
	 */
	default void removeElement(com.top_logic.demo.model.dnd.NamedPlanElement oldValue) {
		tRemoveByName(ELEMENTS_ATTR, oldValue);
	}

}
