/*
 * SPDX-FileCopyrightText: 2022 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.importer.data.struct.impl;

/**
 * Basic interface for {@link #CONTEXT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ContextBase extends test.com.top_logic.importer.data.struct.TestStructContext, test.com.top_logic.importer.data.struct.RootChild {

	/**
	 * Name of type <code>Context</code>
	 */
	String CONTEXT_TYPE = "Context";

	/**
	 * Getter for part {@link #CHILDREN_ATTR}.
	 */
	@Override
	@SuppressWarnings("unchecked")
	default java.util.List<? extends test.com.top_logic.importer.data.struct.ContextChild> getChildren() {
		return (java.util.List<? extends test.com.top_logic.importer.data.struct.ContextChild>) tValueByName(CHILDREN_ATTR);
	}

}
