/*
 * SPDX-FileCopyrightText: 2022 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.importer.data.struct.impl;

/**
 * Basic interface for {@link #TEST_STRUCT_SUB1_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface TestStructSub1Base extends test.com.top_logic.importer.data.struct.TestStructAll {

	/**
	 * Name of type <code>testStruct.Sub1</code>
	 */
	String TEST_STRUCT_SUB1_TYPE = "testStruct.Sub1";

	/**
	 * Part <code>company</code> of <code>testStruct.Sub1</code>
	 * 
	 * <p>
	 * Declared as <code>Contacts:Contact.Company</code> in configuration.
	 * </p>
	 */
	String COMPANY_ATTR = "company";

	/**
	 * Part <code>costs</code> of <code>testStruct.Sub1</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String COSTS_ATTR = "costs";

	/**
	 * Part <code>lead</code> of <code>testStruct.Sub1</code>
	 * 
	 * <p>
	 * Declared as <code>Contacts:Contact.Person</code> in configuration.
	 * </p>
	 */
	String LEAD_ATTR = "lead";

	/**
	 * Getter for part {@link #COMPANY_ATTR}.
	 */
	default com.top_logic.model.TLObject getCompany() {
		return (com.top_logic.model.TLObject) tValueByName(COMPANY_ATTR);
	}

	/**
	 * Setter for part {@link #COMPANY_ATTR}.
	 */
	default void setCompany(com.top_logic.model.TLObject newValue) {
		tUpdateByName(COMPANY_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #COSTS_ATTR}.
	 */
	default Double getCosts() {
		return (Double) tValueByName(COSTS_ATTR);
	}

	/**
	 * Setter for part {@link #COSTS_ATTR}.
	 */
	default void setCosts(Double newValue) {
		tUpdateByName(COSTS_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #LEAD_ATTR}.
	 */
	default com.top_logic.model.TLObject getLead() {
		return (com.top_logic.model.TLObject) tValueByName(LEAD_ATTR);
	}

	/**
	 * Setter for part {@link #LEAD_ATTR}.
	 */
	default void setLead(com.top_logic.model.TLObject newValue) {
		tUpdateByName(LEAD_ATTR, newValue);
	}

}
