/*
 * SPDX-FileCopyrightText: 2022 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.importer.data.struct.impl;

import com.top_logic.knowledge.objects.KnowledgeObject;

/**
 * Wrapper implementation class for <code>testStruct:Sub2</code> business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.ImplementationTemplateGenerator}
 */
public class TestStructSub2Impl extends com.top_logic.element.structured.wrap.AttributedStructuredElementWrapper implements test.com.top_logic.importer.data.struct.Sub2 {

	/**
	 * Default constructor.
	 */
	public TestStructSub2Impl(KnowledgeObject ko) {
		super(ko);
	}

}
