/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.importer.data.struct.impl;

import com.top_logic.knowledge.objects.KnowledgeObject;

/**
 * Wrapper implementation class for <code>testStruct:Context</code> business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.ImplementationTemplateGenerator}
 */
public class TestStructContextImpl extends com.top_logic.element.structured.wrap.AttributedStructuredElementWrapper implements test.com.top_logic.importer.data.struct.Context {

	/**
	 * Default constructor.
	 */
	public TestStructContextImpl(KnowledgeObject ko) {
		super(ko);
	}

}
