/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.demo.model.aspect.wrap;

/**
 * Basic interface for {@link #B_NODE_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface BNodeBase extends com.top_logic.demo.model.aspect.B, com.top_logic.demo.model.aspect.CommonChild {

	/**
	 * Name of type <code>BNode</code>
	 */
	String B_NODE_TYPE = "BNode";

}
