/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.demo.model.aspect.wrap;

/**
 * Basic interface for {@link #C_NODE_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface CNodeBase extends com.top_logic.demo.model.aspect.CommonChild, com.top_logic.demo.model.aspect.C {

	/**
	 * Name of type <code>CNode</code>
	 */
	String C_NODE_TYPE = "CNode";

}
