/*
 * SPDX-FileCopyrightText: 2009 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.basic.generate;

import com.top_logic.basic.StringServices;

/**
 * {@link FileGenerator} to generate Java source files.
 * 
 * @author <a href="mailto:bhu@top-logic.com">Bernhard Haumacher</a>
 */
public abstract class JavaGenerator extends FileGenerator {

	private final String packageName;
	
	public JavaGenerator(String packageName) {
		super(JavaFile.INSTANCE);
		
		this.packageName = packageName;
	}

	@Override
	protected void writeContents() {
		writePackage();
		writeBody();
	}

	protected abstract void writeBody();

	protected void writePackage() {
		line("package " + packageName + ";");
		nl();
	}

	public String packageName() {
		return packageName;
	}
	
	protected void writeCvsTags() {
		writeAuthor();
	}

	protected void writeAuthor() {
		line(" * @author Automatically generated by {@link " + this.getClass().getName().replace('$', '.') + "}");
	}
	
	public void javadocStart() {
		line("/**");
	}
	
	public void javadocStop() {
		line(" */");
	}
	
	public void importLine(String importArg) {
		String importSeparator = ";";
		if (importArg.endsWith(importSeparator)) {
			line("import " + importArg);
		} else {
			line("import " + importArg + importSeparator);
		}
	}

	@Override
	protected void line(String line) {
		if (StringServices.startsWithChar(line, '}')) {
			unindent();
		}
		
		super.line(line);
		
		if (StringServices.endsWithChar(line, '{')) {
			indent();
		}
	}

	@Override
	public String fileName() {
		return className() + ".java";
	}
	
	public abstract String className();

}
