/*
 * SPDX-FileCopyrightText: 2011 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.contact.orgunit;


import com.top_logic.contact.orgunit.impl.AbstractOrgHeadWrapper;
import com.top_logic.knowledge.objects.KnowledgeObject;

/**
 * Wrapper implementation class for <code>OrgUnit.head</code> business objects.
 * 
 * @author Automatically generated by <code>com.top_logic.element.binding.gen.WrapperTemplateGenerator</code>
 */
public class OrganizationHead extends AbstractOrgHeadWrapper {

	/**
	 * Default constructor.
	 */
	public OrganizationHead(KnowledgeObject ko) {
		super(ko);
	}


	// TODO: Implement wrapper functionality.

}
