/*
 * SPDX-FileCopyrightText: 2011 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.contact.orgunit;

/**
 * Constant declarations for <code>OrgUnit.root</code> business objects.
 * 
 * @author Automatically generated by <code>com.top_logic.element.binding.gen.ConstantGenerator</code>
 */
public interface OrgRootConstants extends OrgUnitAllConstants {

	/**
	 * Name of meta element <code>OrgUnit.root</code>
	 */
	String ME_ORG_ROOT = "OrgUnit.root";

}
