/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.demo.model.containmentContext.wrap;

/**
 * Basic interface for {@link #USAGE_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface UsageBase extends com.top_logic.model.TLObject {

	/**
	 * Name of type <code>Usage</code>
	 */
	String USAGE_TYPE = "Usage";

	/**
	 * Part <code>reason</code> of <code>Usage</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String REASON_ATTR = "reason";

	/**
	 * Part <code>subject</code> of <code>Usage</code>
	 * 
	 * <p>
	 * Declared as <code>test.containmentContext:Thing</code> in configuration.
	 * </p>
	 */
	String SUBJECT_ATTR = "subject";

	/**
	 * Part <code>thing</code> of <code>Usage</code>
	 * 
	 * <p>
	 * Declared as <code>test.containmentContext:Thing</code> in configuration.
	 * </p>
	 */
	String THING_ATTR = "thing";

	/**
	 * Getter for part {@link #REASON_ATTR}.
	 */
	default String getReason() {
		return (String) tValueByName(REASON_ATTR);
	}

	/**
	 * Setter for part {@link #REASON_ATTR}.
	 */
	default void setReason(String newValue) {
		tUpdateByName(REASON_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #SUBJECT_ATTR}.
	 */
	default com.top_logic.demo.model.containmentContext.Thing getSubject() {
		return (com.top_logic.demo.model.containmentContext.Thing) tValueByName(SUBJECT_ATTR);
	}

	/**
	 * Getter for part {@link #THING_ATTR}.
	 */
	default com.top_logic.demo.model.containmentContext.Thing getThing() {
		return (com.top_logic.demo.model.containmentContext.Thing) tValueByName(THING_ATTR);
	}

	/**
	 * Setter for part {@link #THING_ATTR}.
	 */
	default void setThing(com.top_logic.demo.model.containmentContext.Thing newValue) {
		tUpdateByName(THING_ATTR, newValue);
	}

}
