CREATE TABLE SELECT (
	# This kind of Comment is not supported with MySQL, Is it ?
 TYPE 		VARCHAR2(70)  NOT NULL,
 TABLE      VARCHAR2(100) NOT NULL, 
 ATTR 		VARCHAR2(70)  NOT NULL,
 VAL_TYPE 	BIGDECIMAL NOT NULL,
 LVAL 		BIGINT ,
 DVAL 		DOUBLE,
 SVAL 		VARCHAR(254),
 TVAL 		TEXT,
 
 PRIMARY KEY (TYPE, IDENTIFIER, ATTR)
);
