/*
 * SPDX-FileCopyrightText: 2023 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.demo.model.types;

/**
 * Factory for <code>DemoTypes</code> objects.
 * 
 * <p>
 * Note: this is generated code. Do not modify. Instead, create a subclass and register this in the module system.
 * </p>
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.FactoryGenerator}
 */
public class DemoTypesFactory extends com.top_logic.element.structured.wrap.StructuredElementWrapperFactory {

	/**
	 * Name of singleton {@link #DEMO_TYPES_STRUCTURE}.
	 */
	public static final String SINGLETON_ROOT = "ROOT";

	/**
	 * Name of the structure <code>DemoTypes</code> defined by {@link DemoTypesFactory}.
	 */
	public static final String DEMO_TYPES_STRUCTURE = "DemoTypes";

	/**
	 * Name of the enumeration <code>DemoEnum</code> in module {@value #DEMO_TYPES_STRUCTURE}.
	 */
	public static final String DEMO_ENUM_ENUM = "DemoEnum";

	/**
	 * Name of the classifier <code>FirstOption</code> in enumeration {@value #DEMO_ENUM_ENUM}.
	 */
	public static final String FIRST_OPTION_DEMO_ENUM_CLASSIFIER = "FirstOption";

	/**
	 * Name of the classifier <code>LastOption</code> in enumeration {@value #DEMO_ENUM_ENUM}.
	 */
	public static final String LAST_OPTION_DEMO_ENUM_CLASSIFIER = "LastOption";

	/**
	 * Name of the classifier <code>MiddleOption</code> in enumeration {@value #DEMO_ENUM_ENUM}.
	 */
	public static final String MIDDLE_OPTION_DEMO_ENUM_CLASSIFIER = "MiddleOption";

	/**
	 * Name of the data type <code>DemoTime</code> in module {@value #DEMO_TYPES_STRUCTURE}.
	 */
	public static final String DEMO_TIME_TYPE = "DemoTime";

	/**
	 * Name of the data type <code>DemoVec</code> in module {@value #DEMO_TYPES_STRUCTURE}.
	 */
	public static final String DEMO_VEC_TYPE = "DemoVec";

	/**
	 * Name of the data type <code>com.top_logic.demo.model.types.util.EncryptedLongMapping.DemoTypes.A.encryptedLong</code> in module {@value #DEMO_TYPES_STRUCTURE}.
	 */
	public static final String COM_TOP_LOGIC_DEMO_MODEL_TYPES_UTIL_ENCRYPTED_LONG_MAPPING_DEMO_TYPES_A_ENCRYPTED_LONG_TYPE = "com.top_logic.demo.model.types.util.EncryptedLongMapping.DemoTypes.A.encryptedLong";

	/**
	 * Name of the data type <code>com.top_logic.demo.model.types.util.EncryptedLongMapping.DemoTypes.X.encryptedLong</code> in module {@value #DEMO_TYPES_STRUCTURE}.
	 */
	public static final String COM_TOP_LOGIC_DEMO_MODEL_TYPES_UTIL_ENCRYPTED_LONG_MAPPING_DEMO_TYPES_X_ENCRYPTED_LONG_TYPE = "com.top_logic.demo.model.types.util.EncryptedLongMapping.DemoTypes.X.encryptedLong";

	/**
	 * Lookup {@link AChild} type.
	 */
	public static com.top_logic.model.TLClass getAChildType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(AChild.A_CHILD_TYPE);
	}

	/**
	 * Lookup {@link BChild} type.
	 */
	public static com.top_logic.model.TLClass getBChildType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(BChild.B_CHILD_TYPE);
	}

	/**
	 * Lookup {@link BNotUnderAChild} type.
	 */
	public static com.top_logic.model.TLClass getBNotUnderAChildType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(BNotUnderAChild.B_NOT_UNDER_A_CHILD_TYPE);
	}

	/**
	 * Lookup {@link CChild} type.
	 */
	public static com.top_logic.model.TLClass getCChildType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(CChild.C_CHILD_TYPE);
	}

	/**
	 * Lookup {@link DemoTypesAll} type.
	 */
	public static com.top_logic.model.TLClass getDemoTypesAllType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(DemoTypesAll.DEMO_TYPES_ALL_TYPE);
	}

	/**
	 * Lookup {@link DemoTypesAll#NAME_ATTR} of {@link DemoTypesAll}.
	 */
	public static com.top_logic.model.TLProperty getNameDemoTypesAllAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAllType().getPart(DemoTypesAll.NAME_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA} type.
	 */
	public static com.top_logic.model.TLClass getDemoTypesAType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(DemoTypesA.DEMO_TYPES_A_TYPE);
	}

	/**
	 * Lookup {@link DemoTypesA#BINARY_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getBinaryDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.BINARY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#BOOLEAN_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getBooleanDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.BOOLEAN_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#BOOLEAN_MANDATORY_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getBooleanMandatoryDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.BOOLEAN_MANDATORY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#BOOLEAN_NULLABLE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getBooleanNullableDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.BOOLEAN_NULLABLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#BOOLEAN_RADIO_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getBooleanRadioDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.BOOLEAN_RADIO_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#BOOLEAN_RADIO_MANDATORY_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getBooleanRadioMandatoryDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.BOOLEAN_RADIO_MANDATORY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#BOOLEAN_RADIO_NULLABLE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getBooleanRadioNullableDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.BOOLEAN_RADIO_NULLABLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#BOOLEAN_SELECT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getBooleanSelectDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.BOOLEAN_SELECT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#BOOLEAN_SELECT_MANDATORY_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getBooleanSelectMandatoryDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.BOOLEAN_SELECT_MANDATORY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#BOOLEAN_SELECT_NULLABLE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getBooleanSelectNullableDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.BOOLEAN_SELECT_NULLABLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#BOOLEAN_WITH_ATTRIBUTE_SECURITY_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getBooleanWithAttributeSecurityDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.BOOLEAN_WITH_ATTRIBUTE_SECURITY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CHECKLIST_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getChecklistDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CHECKLIST_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CHECKLIST_MULTI_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getChecklistMultiDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CHECKLIST_MULTI_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CHECKLIST_SINGLE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getChecklistSingleDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CHECKLIST_SINGLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CLASSIFICATION_LOCAL_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getClassificationLocalDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CLASSIFICATION_LOCAL_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CLASSIFICATION_MULTI_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getClassificationMultiDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CLASSIFICATION_MULTI_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CLASSIFICATION_MULTI_DROPDOWN_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getClassificationMultiDropdownDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CLASSIFICATION_MULTI_DROPDOWN_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CLASSIFICATION_SINGLE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getClassificationSingleDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CLASSIFICATION_SINGLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CLASSIFICATION_SINGLE_LEGACY_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getClassificationSingleLegacyDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CLASSIFICATION_SINGLE_LEGACY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CLASSIFICATION_SINGLE_POPUP_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getClassificationSinglePopupDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CLASSIFICATION_SINGLE_POPUP_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CLASSIFICATION_UNORDERED_MULTI_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getClassificationUnorderedMultiDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CLASSIFICATION_UNORDERED_MULTI_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CLASSIFICATION_UNORDERED_MULTI_DROPDOWN_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getClassificationUnorderedMultiDropdownDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CLASSIFICATION_UNORDERED_MULTI_DROPDOWN_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CLASSIFICATION_UNORDERED_SINGLE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getClassificationUnorderedSingleDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CLASSIFICATION_UNORDERED_SINGLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CLASSIFICATION_UNORDERED_SINGLE_POPUP_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getClassificationUnorderedSinglePopupDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CLASSIFICATION_UNORDERED_SINGLE_POPUP_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#COLLECTION_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getCollectionDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.COLLECTION_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#COLOR_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getColorDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.COLOR_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#COMMENTS_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getCommentsDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.COMMENTS_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#COMPLEX_COUNTRY_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getComplexCountryDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.COMPLEX_COUNTRY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#COMPLEX_LANGUAGE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getComplexLanguageDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.COMPLEX_LANGUAGE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#COMPLEX_UNIT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getComplexUnitDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.COMPLEX_UNIT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CONTAINMENT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getContainmentDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.CONTAINMENT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CREATED_BY_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getCreatedByDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.CREATED_BY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#CREATED_DATE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getCreatedDateDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.CREATED_DATE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#DATE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getDateDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.DATE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#DATE2_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getDate2DemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.DATE2_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#DATE_TIME_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getDateTimeDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.DATE_TIME_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#DEPENDENCY1_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getDependency1DemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.DEPENDENCY1_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#DEPENDENCY2_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getDependency2DemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.DEPENDENCY2_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#DERIVED_PATH_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getDerivedPathDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.DERIVED_PATH_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#DOCUMENT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getDocumentDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.DOCUMENT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#ENCRYPTED_LONG_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getEncryptedLongDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.ENCRYPTED_LONG_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#EXPR_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getExprDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.EXPR_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#FLOAT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getFloatDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.FLOAT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#FLOAT_CONSTRAINT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getFloatConstraintDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.FLOAT_CONSTRAINT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#FLOAT_DEFAULT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getFloatDefaultDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.FLOAT_DEFAULT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#FLOAT_PERCENT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getFloatPercentDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.FLOAT_PERCENT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#FLOAT_SET_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getFloatSetDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.FLOAT_SET_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#GALLERY_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getGalleryDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.GALLERY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#HISTORIC_REFERENCES_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getHistoricReferencesDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.HISTORIC_REFERENCES_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#HISTORIC_WRAPPER_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getHistoricWrapperDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.HISTORIC_WRAPPER_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#HTML_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getHtmlDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.HTML_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#I18NHTML_NORMAL_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getI18NHTMLNormalDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.I18NHTML_NORMAL_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#I18N_STRING_MULTI_LINE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getI18NStringMultiLineDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.I18N_STRING_MULTI_LINE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#I18N_STRING_NORMAL_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getI18NStringNormalDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.I18N_STRING_NORMAL_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#I18N_STRING_SHORT_LENGTH_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getI18NStringShortLengthDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.I18N_STRING_SHORT_LENGTH_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#ICON_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getIconDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.ICON_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#ID_LONG_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getIdLongDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.ID_LONG_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#ID_STRING_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getIdStringDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.ID_STRING_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#INLINE_REFERENCE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getInlineReferenceDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.INLINE_REFERENCE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#INLINE_REFERENCE_REVERSE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getInlineReferenceReverseDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.INLINE_REFERENCE_REVERSE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#INT_LIST_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getIntListDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.INT_LIST_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#INT_LIST_DERIVED_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getIntListDerivedDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.INT_LIST_DERIVED_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#JSON_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getJsonDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.JSON_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#KEYWORD_SET_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getKeywordSetDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.KEYWORD_SET_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#LIST_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getListDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.LIST_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#LONG_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getLongDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.LONG_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#LONG_CONSTRAINT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getLongConstraintDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.LONG_CONSTRAINT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#MODIFIED_BY_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getModifiedByDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.MODIFIED_BY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#MODIFIED_DATE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getModifiedDateDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.MODIFIED_DATE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#OFFSET_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getOffsetDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.OFFSET_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#PASSWORD_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getPasswordDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.PASSWORD_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#PERSON_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getPersonDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.PERSON_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#PRIORITY_TABLE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getPriorityTableDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.PRIORITY_TABLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#REPORT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getReportDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.REPORT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#RESPONSIBLE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getResponsibleDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.RESPONSIBLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#SINGLE_STRUCTURE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getSingleStructureDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.SINGLE_STRUCTURE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#STRING_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getStringDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.STRING_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#STRING_HIDDEN_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getStringHiddenDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.STRING_HIDDEN_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#STRING_LENGTH_CONSTRAINT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getStringLengthConstraintDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.STRING_LENGTH_CONSTRAINT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#STRING_SET_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getStringSetDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.STRING_SET_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#STRING_WITH_ATTRIBUTE_SECURITY_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getStringWithAttributeSecurityDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.STRING_WITH_ATTRIBUTE_SECURITY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#STRUCTURE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getStructureDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.STRUCTURE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#TEMPLATE_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getTemplateDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.TEMPLATE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#TEXT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getTextDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.TEXT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#TEXT1333_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getText1333DemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.TEXT1333_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#TEXT2000_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getText2000DemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.TEXT2000_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#TEXT4000_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getText4000DemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.TEXT4000_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#TIME_UNIT_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getTimeUnitDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.TIME_UNIT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#TYPED_SET_ORDERED_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getTypedSetOrderedDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.TYPED_SET_ORDERED_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#TYPED_SET_UNORDERED_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getTypedSetUnorderedDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.TYPED_SET_UNORDERED_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#TYPED_WRAPPER_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getTypedWrapperDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.TYPED_WRAPPER_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#TYPED_WRAPPER_C_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getTypedWrapperCDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.TYPED_WRAPPER_C_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#TYPED_WRAPPER_FILTERED_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getTypedWrapperFilteredDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.TYPED_WRAPPER_FILTERED_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#TYPED_WRAPPER_GENERATED_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getTypedWrapperGeneratedDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.TYPED_WRAPPER_GENERATED_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#UNTYPED_WRAPPER_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getUntypedWrapperDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.UNTYPED_WRAPPER_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#URL_LINK_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getUrlLinkDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.URL_LINK_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#URL_STRING_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getUrlStringDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.URL_STRING_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#WEB_FOLDER_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLReference getWebFolderDemoTypesAAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesAType().getPart(DemoTypesA.WEB_FOLDER_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesA#XML_ATTR} of {@link DemoTypesA}.
	 */
	public static com.top_logic.model.TLProperty getXmlDemoTypesAAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesAType().getPart(DemoTypesA.XML_ATTR);
	}

	/**
	 * Lookup {@link A} type.
	 */
	public static com.top_logic.model.TLClass getAType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(A.A_TYPE);
	}

	/**
	 * Lookup {@link A#CHILDREN_ATTR} of {@link A}.
	 */
	public static com.top_logic.model.TLReference getChildrenAAttr() {
		return (com.top_logic.model.TLReference) getAType().getPart(A.CHILDREN_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesBC} type.
	 */
	public static com.top_logic.model.TLClass getDemoTypesBCType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(DemoTypesBC.DEMO_TYPES_BC_TYPE);
	}

	/**
	 * Lookup {@link DemoTypesBC#STRUCTURE_REVERSE_ATTR} of {@link DemoTypesBC}.
	 */
	public static com.top_logic.model.TLReference getStructureReverseDemoTypesBCAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesBCType().getPart(DemoTypesBC.STRUCTURE_REVERSE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesBC#TYPED_WRAPPER_C_REVERSE_ATTR} of {@link DemoTypesBC}.
	 */
	public static com.top_logic.model.TLReference getTypedWrapperCReverseDemoTypesBCAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesBCType().getPart(DemoTypesBC.TYPED_WRAPPER_C_REVERSE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesB} type.
	 */
	public static com.top_logic.model.TLClass getDemoTypesBType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(DemoTypesB.DEMO_TYPES_B_TYPE);
	}

	/**
	 * Lookup {@link DemoTypesB#ENUM_IN_B_AND_C_ATTR} of {@link DemoTypesB}.
	 */
	public static com.top_logic.model.TLReference getEnumInBAndCDemoTypesBAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesBType().getPart(DemoTypesB.ENUM_IN_B_AND_C_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesB#GENERIC_IN_B_AND_C_ATTR} of {@link DemoTypesB}.
	 */
	public static com.top_logic.model.TLProperty getGenericInBAndCDemoTypesBAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesBType().getPart(DemoTypesB.GENERIC_IN_B_AND_C_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesB#STRING_IN_B_AND_C_ATTR} of {@link DemoTypesB}.
	 */
	public static com.top_logic.model.TLProperty getStringInBAndCDemoTypesBAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesBType().getPart(DemoTypesB.STRING_IN_B_AND_C_ATTR);
	}

	/**
	 * Lookup {@link B} type.
	 */
	public static com.top_logic.model.TLClass getBType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(B.B_TYPE);
	}

	/**
	 * Lookup {@link B#CHILDREN_ATTR} of {@link B}.
	 */
	public static com.top_logic.model.TLReference getChildrenBAttr() {
		return (com.top_logic.model.TLReference) getBType().getPart(B.CHILDREN_ATTR);
	}

	/**
	 * Lookup {@link BNotUnderA} type.
	 */
	public static com.top_logic.model.TLClass getBNotUnderAType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(BNotUnderA.B_NOT_UNDER_A_TYPE);
	}

	/**
	 * Lookup {@link BNotUnderA#CHILDREN_ATTR} of {@link BNotUnderA}.
	 */
	public static com.top_logic.model.TLReference getChildrenBNotUnderAAttr() {
		return (com.top_logic.model.TLReference) getBNotUnderAType().getPart(BNotUnderA.CHILDREN_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesCAll} type.
	 */
	public static com.top_logic.model.TLClass getDemoTypesCAllType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(DemoTypesCAll.DEMO_TYPES_C_ALL_TYPE);
	}

	/**
	 * Lookup {@link DemoTypesCAll#DEPENDENT_DATE_ATTR} of {@link DemoTypesCAll}.
	 */
	public static com.top_logic.model.TLProperty getDependentDateDemoTypesCAllAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesCAllType().getPart(DemoTypesCAll.DEPENDENT_DATE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesCAll#ENUM_IN_B_AND_C_ATTR} of {@link DemoTypesCAll}.
	 */
	public static com.top_logic.model.TLReference getEnumInBAndCDemoTypesCAllAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesCAllType().getPart(DemoTypesCAll.ENUM_IN_B_AND_C_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesCAll#GENERIC_IN_B_AND_C_ATTR} of {@link DemoTypesCAll}.
	 */
	public static com.top_logic.model.TLProperty getGenericInBAndCDemoTypesCAllAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesCAllType().getPart(DemoTypesCAll.GENERIC_IN_B_AND_C_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesCAll#IS_ASSIGNABLE_ATTR} of {@link DemoTypesCAll}.
	 */
	public static com.top_logic.model.TLProperty getIsAssignableDemoTypesCAllAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesCAllType().getPart(DemoTypesCAll.IS_ASSIGNABLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesCAll#MACRO_ATTR} of {@link DemoTypesCAll}.
	 */
	public static com.top_logic.model.TLProperty getMacroDemoTypesCAllAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesCAllType().getPart(DemoTypesCAll.MACRO_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesCAll#PRIORITY_TABLE_DIALOG_CONFIG_ATTR} of {@link DemoTypesCAll}.
	 */
	public static com.top_logic.model.TLReference getPriorityTableDialogConfigDemoTypesCAllAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesCAllType().getPart(DemoTypesCAll.PRIORITY_TABLE_DIALOG_CONFIG_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesCAll#STRING_IN_B_AND_C_ATTR} of {@link DemoTypesCAll}.
	 */
	public static com.top_logic.model.TLProperty getStringInBAndCDemoTypesCAllAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesCAllType().getPart(DemoTypesCAll.STRING_IN_B_AND_C_ATTR);
	}

	/**
	 * Lookup {@link C} type.
	 */
	public static com.top_logic.model.TLClass getCType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(C.C_TYPE);
	}

	/**
	 * Lookup {@link C#CHILDREN_ATTR} of {@link C}.
	 */
	public static com.top_logic.model.TLReference getChildrenCAttr() {
		return (com.top_logic.model.TLReference) getCType().getPart(C.CHILDREN_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesL} type.
	 */
	public static com.top_logic.model.TLClass getDemoTypesLType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(DemoTypesL.DEMO_TYPES_L_TYPE);
	}

	/**
	 * Lookup {@link DemoTypesL#DATE_WITH_DEFAULT_ATTR} of {@link DemoTypesL}.
	 */
	public static com.top_logic.model.TLProperty getDateWithDefaultDemoTypesLAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesLType().getPart(DemoTypesL.DATE_WITH_DEFAULT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesL#PLAIN_CHILDREN_ATTR} of {@link DemoTypesL}.
	 */
	public static com.top_logic.model.TLReference getPlainChildrenDemoTypesLAttr() {
		return (com.top_logic.model.TLReference) getDemoTypesLType().getPart(DemoTypesL.PLAIN_CHILDREN_ATTR);
	}

	/**
	 * Lookup {@link L} type.
	 */
	public static com.top_logic.model.TLClass getLType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(L.L_TYPE);
	}

	/**
	 * Lookup {@link DemoTypesX} type.
	 */
	public static com.top_logic.model.TLClass getDemoTypesXType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(DemoTypesX.DEMO_TYPES_X_TYPE);
	}

	/**
	 * Lookup {@link DemoTypesX#BINARY_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getBinaryDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.BINARY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#BOOLEAN_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getBooleanDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.BOOLEAN_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#BOOLEAN_MANDATORY_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getBooleanMandatoryDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.BOOLEAN_MANDATORY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#BOOLEAN_NULLABLE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getBooleanNullableDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.BOOLEAN_NULLABLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#BOOLEAN_RADIO_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getBooleanRadioDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.BOOLEAN_RADIO_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#BOOLEAN_RADIO_MANDATORY_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getBooleanRadioMandatoryDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.BOOLEAN_RADIO_MANDATORY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#BOOLEAN_RADIO_NULLABLE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getBooleanRadioNullableDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.BOOLEAN_RADIO_NULLABLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#BOOLEAN_SELECT_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getBooleanSelectDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.BOOLEAN_SELECT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#BOOLEAN_SELECT_MANDATORY_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getBooleanSelectMandatoryDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.BOOLEAN_SELECT_MANDATORY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#BOOLEAN_SELECT_NULLABLE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getBooleanSelectNullableDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.BOOLEAN_SELECT_NULLABLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#BOOLEAN_WITH_ATTRIBUTE_SECURITY_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getBooleanWithAttributeSecurityDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.BOOLEAN_WITH_ATTRIBUTE_SECURITY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CHECKLIST_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getChecklistDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CHECKLIST_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CHECKLIST_MULTI_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getChecklistMultiDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CHECKLIST_MULTI_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CHECKLIST_SINGLE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getChecklistSingleDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CHECKLIST_SINGLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CLASSIFICATION_MULTI_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getClassificationMultiDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CLASSIFICATION_MULTI_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CLASSIFICATION_MULTI_DROPDOWN_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getClassificationMultiDropdownDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CLASSIFICATION_MULTI_DROPDOWN_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CLASSIFICATION_SINGLE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getClassificationSingleDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CLASSIFICATION_SINGLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CLASSIFICATION_SINGLE_POPUP_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getClassificationSinglePopupDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CLASSIFICATION_SINGLE_POPUP_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CLASSIFICATION_UNORDERED_MULTI_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getClassificationUnorderedMultiDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CLASSIFICATION_UNORDERED_MULTI_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CLASSIFICATION_UNORDERED_MULTI_DROPDOWN_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getClassificationUnorderedMultiDropdownDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CLASSIFICATION_UNORDERED_MULTI_DROPDOWN_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CLASSIFICATION_UNORDERED_SINGLE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getClassificationUnorderedSingleDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CLASSIFICATION_UNORDERED_SINGLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CLASSIFICATION_UNORDERED_SINGLE_POPUP_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getClassificationUnorderedSinglePopupDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CLASSIFICATION_UNORDERED_SINGLE_POPUP_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#COLLECTION_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getCollectionDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.COLLECTION_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#COMMENTS_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getCommentsDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.COMMENTS_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#COMPLEX_COUNTRY_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getComplexCountryDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.COMPLEX_COUNTRY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#COMPLEX_LANGUAGE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getComplexLanguageDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.COMPLEX_LANGUAGE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#COMPLEX_UNIT_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getComplexUnitDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.COMPLEX_UNIT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CREATED_BY_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getCreatedByDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CREATED_BY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#CREATED_DATE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getCreatedDateDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.CREATED_DATE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#DATE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getDateDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.DATE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#DATE2_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getDate2DemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.DATE2_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#DATE_TIME_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getDateTimeDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.DATE_TIME_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#DOCUMENT_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getDocumentDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.DOCUMENT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#ENCRYPTED_LONG_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getEncryptedLongDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.ENCRYPTED_LONG_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#FLOAT_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getFloatDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.FLOAT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#FLOAT_CONSTRAINT_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getFloatConstraintDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.FLOAT_CONSTRAINT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#FLOAT_DEFAULT_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getFloatDefaultDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.FLOAT_DEFAULT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#FLOAT_PERCENT_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getFloatPercentDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.FLOAT_PERCENT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#GALLERY_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getGalleryDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.GALLERY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#HISTORIC_WRAPPER_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getHistoricWrapperDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.HISTORIC_WRAPPER_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#HTML_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getHtmlDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.HTML_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#I18NHTML_NORMAL_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getI18NHTMLNormalDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.I18NHTML_NORMAL_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#I18N_STRING_MULTI_LINE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getI18NStringMultiLineDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.I18N_STRING_MULTI_LINE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#I18N_STRING_NORMAL_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getI18NStringNormalDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.I18N_STRING_NORMAL_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#I18N_STRING_SHORT_LENGTH_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getI18NStringShortLengthDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.I18N_STRING_SHORT_LENGTH_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#INLINE_REFERENCE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getInlineReferenceDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.INLINE_REFERENCE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#LIST_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getListDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.LIST_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#LONG_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getLongDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.LONG_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#LONG_CONSTRAINT_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getLongConstraintDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.LONG_CONSTRAINT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#MODIFIED_BY_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getModifiedByDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.MODIFIED_BY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#MODIFIED_DATE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getModifiedDateDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.MODIFIED_DATE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#PERSON_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getPersonDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.PERSON_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#PRIORITY_TABLE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getPriorityTableDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.PRIORITY_TABLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#RESPONSIBLE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getResponsibleDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.RESPONSIBLE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#SINGLE_STRUCTURE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getSingleStructureDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.SINGLE_STRUCTURE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#STRING_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getStringDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.STRING_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#STRING_HIDDEN_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getStringHiddenDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.STRING_HIDDEN_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#STRING_LENGTH_CONSTRAINT_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getStringLengthConstraintDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.STRING_LENGTH_CONSTRAINT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#STRING_SET_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getStringSetDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.STRING_SET_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#STRING_WITH_ATTRIBUTE_SECURITY_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getStringWithAttributeSecurityDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.STRING_WITH_ATTRIBUTE_SECURITY_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#STRUCTURE_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getStructureDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.STRUCTURE_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#TEXT_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getTextDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.TEXT_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#TYPED_SET_ORDERED_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getTypedSetOrderedDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.TYPED_SET_ORDERED_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#TYPED_SET_UNORDERED_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getTypedSetUnorderedDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.TYPED_SET_UNORDERED_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#TYPED_WRAPPER_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getTypedWrapperDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.TYPED_WRAPPER_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#TYPED_WRAPPER_C_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getTypedWrapperCDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.TYPED_WRAPPER_C_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#TYPED_WRAPPER_FILTERED_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getTypedWrapperFilteredDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.TYPED_WRAPPER_FILTERED_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#TYPED_WRAPPER_GENERATED_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getTypedWrapperGeneratedDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.TYPED_WRAPPER_GENERATED_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#UNTYPED_WRAPPER_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getUntypedWrapperDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.UNTYPED_WRAPPER_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesX#WEB_FOLDER_ATTR} of {@link DemoTypesX}.
	 */
	public static com.top_logic.model.TLProperty getWebFolderDemoTypesXAttr() {
		return (com.top_logic.model.TLProperty) getDemoTypesXType().getPart(DemoTypesX.WEB_FOLDER_ATTR);
	}

	/**
	 * Lookup {@link X} type.
	 */
	public static com.top_logic.model.TLClass getXType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(X.X_TYPE);
	}

	/**
	 * Lookup {@link P} type.
	 */
	public static com.top_logic.model.TLClass getPType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(P.P_TYPE);
	}

	/**
	 * Lookup {@link P#PROTECTED_ATTR} of {@link P}.
	 */
	public static com.top_logic.model.TLProperty getProtectedPAttr() {
		return (com.top_logic.model.TLProperty) getPType().getPart(P.PROTECTED_ATTR);
	}

	/**
	 * Lookup {@link PP} type.
	 */
	public static com.top_logic.model.TLClass getPPType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(PP.PP_TYPE);
	}

	/**
	 * Lookup {@link PP#MORE_PROTECTED_ATTR} of {@link PP}.
	 */
	public static com.top_logic.model.TLProperty getMoreProtectedPPAttr() {
		return (com.top_logic.model.TLProperty) getPPType().getPart(PP.MORE_PROTECTED_ATTR);
	}

	/**
	 * Lookup {@link PX} type.
	 */
	public static com.top_logic.model.TLClass getPXType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(PX.PX_TYPE);
	}

	/**
	 * Lookup {@link PX#ALTERNATIVE_PROTECTED_ATTR} of {@link PX}.
	 */
	public static com.top_logic.model.TLProperty getAlternativeProtectedPXAttr() {
		return (com.top_logic.model.TLProperty) getPXType().getPart(PX.ALTERNATIVE_PROTECTED_ATTR);
	}

	/**
	 * Lookup {@link DemoTypesRoot} type.
	 */
	public static com.top_logic.model.TLClass getDemoTypesRootType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(DemoTypesRoot.DEMO_TYPES_ROOT_TYPE);
	}

	/**
	 * Lookup {@link Root} type.
	 */
	public static com.top_logic.model.TLClass getRootType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(Root.ROOT_TYPE);
	}

	/**
	 * Lookup {@link Root#CHILDREN_ATTR} of {@link Root}.
	 */
	public static com.top_logic.model.TLReference getChildrenRootAttr() {
		return (com.top_logic.model.TLReference) getRootType().getPart(Root.CHILDREN_ATTR);
	}

	/**
	 * Lookup {@link Root#NAME_ATTR} of {@link Root}.
	 */
	public static com.top_logic.model.TLProperty getNameRootAttr() {
		return (com.top_logic.model.TLProperty) getRootType().getPart(Root.NAME_ATTR);
	}

	/**
	 * Lookup {@link RootChild} type.
	 */
	public static com.top_logic.model.TLClass getRootChildType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(RootChild.ROOT_CHILD_TYPE);
	}

	/**
	 * Lookup {@value #DEMO_ENUM_ENUM} enumeration.
	 */
	public static com.top_logic.model.TLEnumeration getDemoEnumEnum() {
		return (com.top_logic.model.TLEnumeration) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(DEMO_ENUM_ENUM);
	}

	/**
	 * Lookup classifier {@value #FIRST_OPTION_DEMO_ENUM_CLASSIFIER} of enumeration {@value #DEMO_ENUM_ENUM}.
	 */
	public static com.top_logic.model.TLClassifier getFirstOptionDemoEnumClassifier() {
		return getDemoEnumEnum().getClassifier(FIRST_OPTION_DEMO_ENUM_CLASSIFIER);
	}

	/**
	 * Lookup classifier {@value #LAST_OPTION_DEMO_ENUM_CLASSIFIER} of enumeration {@value #DEMO_ENUM_ENUM}.
	 */
	public static com.top_logic.model.TLClassifier getLastOptionDemoEnumClassifier() {
		return getDemoEnumEnum().getClassifier(LAST_OPTION_DEMO_ENUM_CLASSIFIER);
	}

	/**
	 * Lookup classifier {@value #MIDDLE_OPTION_DEMO_ENUM_CLASSIFIER} of enumeration {@value #DEMO_ENUM_ENUM}.
	 */
	public static com.top_logic.model.TLClassifier getMiddleOptionDemoEnumClassifier() {
		return getDemoEnumEnum().getClassifier(MIDDLE_OPTION_DEMO_ENUM_CLASSIFIER);
	}

	/**
	 * Lookup {@value #DEMO_TIME_TYPE} data type.
	 */
	public static com.top_logic.model.TLPrimitive getDemoTimeType() {
		return (com.top_logic.model.TLPrimitive) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(DEMO_TIME_TYPE);
	}

	/**
	 * Lookup {@value #DEMO_VEC_TYPE} data type.
	 */
	public static com.top_logic.model.TLPrimitive getDemoVecType() {
		return (com.top_logic.model.TLPrimitive) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(DEMO_VEC_TYPE);
	}

	/**
	 * Lookup {@value #COM_TOP_LOGIC_DEMO_MODEL_TYPES_UTIL_ENCRYPTED_LONG_MAPPING_DEMO_TYPES_A_ENCRYPTED_LONG_TYPE} data type.
	 */
	public static com.top_logic.model.TLPrimitive getComTopLogicDemoModelTypesUtilEncryptedLongMappingDemoTypesAEncryptedLongType() {
		return (com.top_logic.model.TLPrimitive) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(COM_TOP_LOGIC_DEMO_MODEL_TYPES_UTIL_ENCRYPTED_LONG_MAPPING_DEMO_TYPES_A_ENCRYPTED_LONG_TYPE);
	}

	/**
	 * Lookup {@value #COM_TOP_LOGIC_DEMO_MODEL_TYPES_UTIL_ENCRYPTED_LONG_MAPPING_DEMO_TYPES_X_ENCRYPTED_LONG_TYPE} data type.
	 */
	public static com.top_logic.model.TLPrimitive getComTopLogicDemoModelTypesUtilEncryptedLongMappingDemoTypesXEncryptedLongType() {
		return (com.top_logic.model.TLPrimitive) com.top_logic.util.model.ModelService.getApplicationModel().getModule(DEMO_TYPES_STRUCTURE).getType(COM_TOP_LOGIC_DEMO_MODEL_TYPES_UTIL_ENCRYPTED_LONG_MAPPING_DEMO_TYPES_X_ENCRYPTED_LONG_TYPE);
	}

	/**
	 * Name of type <code>AChild</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link AChild#A_CHILD_TYPE}.
	 */
	@Deprecated
	public static final String A_CHILD_NODE = AChild.A_CHILD_TYPE;

	/**
	 * Name of type <code>BChild</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link BChild#B_CHILD_TYPE}.
	 */
	@Deprecated
	public static final String B_CHILD_NODE = BChild.B_CHILD_TYPE;

	/**
	 * Name of type <code>BNotUnderAChild</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link BNotUnderAChild#B_NOT_UNDER_A_CHILD_TYPE}.
	 */
	@Deprecated
	public static final String B_NOT_UNDER_A_CHILD_NODE = BNotUnderAChild.B_NOT_UNDER_A_CHILD_TYPE;

	/**
	 * Name of type <code>CChild</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link CChild#C_CHILD_TYPE}.
	 */
	@Deprecated
	public static final String C_CHILD_NODE = CChild.C_CHILD_TYPE;

	/**
	 * Name of type <code>DemoTypes.All</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link DemoTypesAll#DEMO_TYPES_ALL_TYPE}.
	 */
	@Deprecated
	public static final String DEMO_TYPES_ALL_NODE = DemoTypesAll.DEMO_TYPES_ALL_TYPE;

	/**
	 * Name of type <code>DemoTypes.A</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link DemoTypesA#DEMO_TYPES_A_TYPE}.
	 */
	@Deprecated
	public static final String DEMO_TYPES_A_NODE = DemoTypesA.DEMO_TYPES_A_TYPE;

	/**
	 * Name of type <code>A</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link A#A_TYPE}.
	 */
	@Deprecated
	public static final String A_NODE = A.A_TYPE;

	/**
	 * Storage table name of {@link #A_NODE} objects.
	 */
	public static final String KO_NAME_A = "DemoTypes";

	/**
	 * Name of type <code>DemoTypes.BC</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link DemoTypesBC#DEMO_TYPES_BC_TYPE}.
	 */
	@Deprecated
	public static final String DEMO_TYPES_BC_NODE = DemoTypesBC.DEMO_TYPES_BC_TYPE;

	/**
	 * Name of type <code>DemoTypes.B</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link DemoTypesB#DEMO_TYPES_B_TYPE}.
	 */
	@Deprecated
	public static final String DEMO_TYPES_B_NODE = DemoTypesB.DEMO_TYPES_B_TYPE;

	/**
	 * Name of type <code>B</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link B#B_TYPE}.
	 */
	@Deprecated
	public static final String B_NODE = B.B_TYPE;

	/**
	 * Storage table name of {@link #B_NODE} objects.
	 */
	public static final String KO_NAME_B = "DemoTypes";

	/**
	 * Name of type <code>BNotUnderA</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link BNotUnderA#B_NOT_UNDER_A_TYPE}.
	 */
	@Deprecated
	public static final String B_NOT_UNDER_A_NODE = BNotUnderA.B_NOT_UNDER_A_TYPE;

	/**
	 * Storage table name of {@link #B_NOT_UNDER_A_NODE} objects.
	 */
	public static final String KO_NAME_B_NOT_UNDER_A = "DemoTypes";

	/**
	 * Name of type <code>DemoTypes.C.All</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link DemoTypesCAll#DEMO_TYPES_C_ALL_TYPE}.
	 */
	@Deprecated
	public static final String DEMO_TYPES_C_ALL_NODE = DemoTypesCAll.DEMO_TYPES_C_ALL_TYPE;

	/**
	 * Name of type <code>C</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link C#C_TYPE}.
	 */
	@Deprecated
	public static final String C_NODE = C.C_TYPE;

	/**
	 * Name of type <code>DemoTypes.L</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link DemoTypesL#DEMO_TYPES_L_TYPE}.
	 */
	@Deprecated
	public static final String DEMO_TYPES_L_NODE = DemoTypesL.DEMO_TYPES_L_TYPE;

	/**
	 * Name of type <code>L</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link L#L_TYPE}.
	 */
	@Deprecated
	public static final String L_NODE = L.L_TYPE;

	/**
	 * Storage table name of {@link #L_NODE} objects.
	 */
	public static final String KO_NAME_L = "DemoTypes";

	/**
	 * Name of type <code>DemoTypes.X</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link DemoTypesX#DEMO_TYPES_X_TYPE}.
	 */
	@Deprecated
	public static final String DEMO_TYPES_X_NODE = DemoTypesX.DEMO_TYPES_X_TYPE;

	/**
	 * Name of type <code>X</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link X#X_TYPE}.
	 */
	@Deprecated
	public static final String X_NODE = X.X_TYPE;

	/**
	 * Storage table name of {@link #X_NODE} objects.
	 */
	public static final String KO_NAME_X = "GenericObject";

	/**
	 * Name of type <code>P</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link P#P_TYPE}.
	 */
	@Deprecated
	public static final String P_NODE = P.P_TYPE;

	/**
	 * Storage table name of {@link #P_NODE} objects.
	 */
	public static final String KO_NAME_P = "DemoTypes";

	/**
	 * Name of type <code>PP</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link PP#PP_TYPE}.
	 */
	@Deprecated
	public static final String PP_NODE = PP.PP_TYPE;

	/**
	 * Storage table name of {@link #PP_NODE} objects.
	 */
	public static final String KO_NAME_PP = "DemoTypes";

	/**
	 * Name of type <code>PX</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link PX#PX_TYPE}.
	 */
	@Deprecated
	public static final String PX_NODE = PX.PX_TYPE;

	/**
	 * Storage table name of {@link #PX_NODE} objects.
	 */
	public static final String KO_NAME_PX = "DemoTypes";

	/**
	 * Name of type <code>DemoTypes.Root</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link DemoTypesRoot#DEMO_TYPES_ROOT_TYPE}.
	 */
	@Deprecated
	public static final String DEMO_TYPES_ROOT_NODE = DemoTypesRoot.DEMO_TYPES_ROOT_TYPE;

	/**
	 * Name of type <code>Root</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link Root#ROOT_TYPE}.
	 */
	@Deprecated
	public static final String ROOT_NODE = Root.ROOT_TYPE;

	/**
	 * Storage table name of {@link #ROOT_NODE} objects.
	 */
	public static final String KO_NAME_ROOT = "DemoTypes";

	/**
	 * Name of type <code>RootChild</code> in structure {@link #DEMO_TYPES_STRUCTURE}.
	 * 
	 * @deprecated Use {@link RootChild#ROOT_CHILD_TYPE}.
	 */
	@Deprecated
	public static final String ROOT_CHILD_NODE = RootChild.ROOT_CHILD_TYPE;

	/**
	 * Singleton <code>ROOT</code>.
	 */
	public Root getRootSingleton() {
		return (Root) lookupSingleton(SINGLETON_ROOT);
	}

	/**
	 * Singleton <code>ROOT</code> on given branch.
	 */
	public Root getRootSingleton(com.top_logic.knowledge.service.Branch requestedBranch) {
		return (Root) lookupSingleton(SINGLETON_ROOT, requestedBranch);
	}

	/**
	 * Singleton <code>ROOT</code> on given branch in given revision.
	 */
	public Root getRootSingleton(com.top_logic.knowledge.service.Branch requestedBranch, com.top_logic.knowledge.service.Revision historyContext) {
		return (Root) lookupSingleton(SINGLETON_ROOT, requestedBranch, historyContext);
	}


	/**
	 * Create an instance of {@link A} type.
	 */
	public final A createA(com.top_logic.model.TLObject context) {
		return (A) createObject(getAType(), context);
	}

	/**
	 * Create an instance of {@link A} type.
	 */
	public final A createA() {
		return createA(null);
	}

	/**
	 * Create an instance of {@link B} type.
	 */
	public final B createB(com.top_logic.model.TLObject context) {
		return (B) createObject(getBType(), context);
	}

	/**
	 * Create an instance of {@link B} type.
	 */
	public final B createB() {
		return createB(null);
	}

	/**
	 * Create an instance of {@link BNotUnderA} type.
	 */
	public final BNotUnderA createBNotUnderA(com.top_logic.model.TLObject context) {
		return (BNotUnderA) createObject(getBNotUnderAType(), context);
	}

	/**
	 * Create an instance of {@link BNotUnderA} type.
	 */
	public final BNotUnderA createBNotUnderA() {
		return createBNotUnderA(null);
	}

	/**
	 * Create an instance of {@link L} type.
	 */
	public final L createL(com.top_logic.model.TLObject context) {
		return (L) createObject(getLType(), context);
	}

	/**
	 * Create an instance of {@link L} type.
	 */
	public final L createL() {
		return createL(null);
	}

	/**
	 * Create an instance of {@link X} type.
	 */
	public final X createX(com.top_logic.model.TLObject context) {
		return (X) createObject(getXType(), context);
	}

	/**
	 * Create an instance of {@link X} type.
	 */
	public final X createX() {
		return createX(null);
	}

	/**
	 * Create an instance of {@link P} type.
	 */
	public final P createP(com.top_logic.model.TLObject context) {
		return (P) createObject(getPType(), context);
	}

	/**
	 * Create an instance of {@link P} type.
	 */
	public final P createP() {
		return createP(null);
	}

	/**
	 * Create an instance of {@link PP} type.
	 */
	public final PP createPP(com.top_logic.model.TLObject context) {
		return (PP) createObject(getPPType(), context);
	}

	/**
	 * Create an instance of {@link PP} type.
	 */
	public final PP createPP() {
		return createPP(null);
	}

	/**
	 * Create an instance of {@link PX} type.
	 */
	public final PX createPX(com.top_logic.model.TLObject context) {
		return (PX) createObject(getPXType(), context);
	}

	/**
	 * Create an instance of {@link PX} type.
	 */
	public final PX createPX() {
		return createPX(null);
	}

	/**
	 * Create an instance of {@link Root} type.
	 */
	public final Root createRoot(com.top_logic.model.TLObject context) {
		return (Root) createObject(getRootType(), context);
	}

	/**
	 * Create an instance of {@link Root} type.
	 */
	public final Root createRoot() {
		return createRoot(null);
	}

	/**
	 * The singleton instance of {@link DemoTypesFactory}.
	 */
	public static DemoTypesFactory getInstance() {
		return (DemoTypesFactory) com.top_logic.element.model.DynamicModelService.getFactoryFor(DEMO_TYPES_STRUCTURE);
	}
}
