/*
 * SPDX-FileCopyrightText: 2002 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.knowledge.journal;

import java.util.Collection;

/**
 * The journal result holds the info about a single commit.
 * 
 * It is used as dataholder when requesting journals.
 * 
 * @history	  2004-04-30    dkh    changed to commitInfo-holder with JournalResultEntries containing the data
 * @author    <a href="mailto:tsa@top-logic.com">Theo Sattler</a>
 * 
 */
public class JournalResult {
    
    /** The comit id as generated by the database */
    public long   commitId;
	
	/** time of commit as long to build a java.util.Date from */
	public long   timeMillis;
    
    /** the user doing the commit */
    public String userID; 

	/** the Entries per KO of this commit */
	public Collection<JournalResultEntry>  entries;
    
    /**
     * Constructor
     */
    public JournalResult(long aCommitId, long aTimeMillis, String aUserID, Collection someEntries) {
        this.commitId = aCommitId;
        this.userID   = aUserID;
        this.entries  = someEntries;
        this.timeMillis = aTimeMillis;
    }

    public void setEntries(Collection<JournalResultEntry> someEntries) {
        this.entries = someEntries;
    }
	
	/** 
	 * overwritten for use as identifier in Table 
	 * @return commitId to identify JournalResult
	 */
	@Override
	public String toString() {
		return String.valueOf(commitId);
	}
	
}
