/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.element.changelog.model.impl;

/**
 * Basic interface for {@link #CREATE_OP_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface CreateOpBase extends com.top_logic.element.changelog.model.Operation {

	/**
	 * Name of type <code>CreateOp</code>
	 */
	String CREATE_OP_TYPE = "CreateOp";

	/**
	 * Part <code>id</code> of <code>CreateOp</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Long</code> in configuration.
	 * </p>
	 */
	String ID_ATTR = "id";

	/**
	 * Part <code>initializers</code> of <code>CreateOp</code>
	 * 
	 * <p>
	 * Declared as <code>tl.changelog:SetOp</code> in configuration.
	 * </p>
	 */
	String INITIALIZERS_ATTR = "initializers";

	/**
	 * Part <code>type</code> of <code>CreateOp</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model:TLClass</code> in configuration.
	 * </p>
	 */
	String TYPE_ATTR = "type";

	/**
	 * Getter for part {@link #ID_ATTR}.
	 */
	default Long getId() {
		return (Long) tValueByName(ID_ATTR);
	}

	/**
	 * Setter for part {@link #ID_ATTR}.
	 */
	default void setId(Long newValue) {
		tUpdateByName(ID_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #INITIALIZERS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.List<? extends com.top_logic.element.changelog.model.SetOp> getInitializers() {
		return (java.util.List<? extends com.top_logic.element.changelog.model.SetOp>) tValueByName(INITIALIZERS_ATTR);
	}

	/**
	 * Live view of the {@link #INITIALIZERS_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.List<com.top_logic.element.changelog.model.SetOp> getInitializersModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(INITIALIZERS_ATTR);
		@SuppressWarnings("unchecked")
		java.util.List<com.top_logic.element.changelog.model.SetOp> result = (java.util.List<com.top_logic.element.changelog.model.SetOp>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #INITIALIZERS_ATTR}.
	 */
	default void setInitializers(java.util.List<com.top_logic.element.changelog.model.SetOp> newValue) {
		tUpdateByName(INITIALIZERS_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #INITIALIZERS_ATTR} reference.
	 */
	default void addInitializer(com.top_logic.element.changelog.model.SetOp newValue) {
		tAddByName(INITIALIZERS_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #INITIALIZERS_ATTR} reference.
	 */
	default void removeInitializer(com.top_logic.element.changelog.model.SetOp oldValue) {
		tRemoveByName(INITIALIZERS_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #TYPE_ATTR}.
	 */
	default com.top_logic.model.TLClass getType() {
		return (com.top_logic.model.TLClass) tValueByName(TYPE_ATTR);
	}

	/**
	 * Setter for part {@link #TYPE_ATTR}.
	 */
	default void setType(com.top_logic.model.TLClass newValue) {
		tUpdateByName(TYPE_ATTR, newValue);
	}

}
