<!--
	included by top-logic/jsp/layout/webfolder/UploadFile.jsp
	to insert additional inputs or infos below the file choosing.
-->
<!--
	This is a dummy file without content to explain usage.
	if you wish to extend the form of the upload dialog, do it as follows:
	
	- overwrite this file in your application, i.e. add file in same path below your context
	- insert TABLE ROWS with your labels and input fields
-->