/* Generated By:JavaCC: Do not edit this line. SearchExpressionParserConstants.java */
/*
 * SPDX-FileCopyrightText: 2018 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.model.search.expr.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SearchExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int TAB = 2;
  /** RegularExpression Id. */
  int CR = 3;
  /** RegularExpression Id. */
  int NL = 4;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 5;
  /** RegularExpression Id. */
  int LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int TRUE = 7;
  /** RegularExpression Id. */
  int FALSE = 8;
  /** RegularExpression Id. */
  int NULL = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int THIS = 12;
  /** RegularExpression Id. */
  int TUPLE = 13;
  /** RegularExpression Id. */
  int SWITCH = 14;
  /** RegularExpression Id. */
  int DEFAULT_KEYWORRD = 15;
  /** RegularExpression Id. */
  int NAME = 16;
  /** RegularExpression Id. */
  int VAR = 17;
  /** RegularExpression Id. */
  int STRING = 18;
  /** RegularExpression Id. */
  int RESKEY = 19;
  /** RegularExpression Id. */
  int LANGTAG = 20;
  /** RegularExpression Id. */
  int QUOTE = 21;
  /** RegularExpression Id. */
  int NUM = 22;
  /** RegularExpression Id. */
  int MODEL_NAME = 23;
  /** RegularExpression Id. */
  int MODULE = 24;
  /** RegularExpression Id. */
  int TYPE = 25;
  /** RegularExpression Id. */
  int PART = 26;
  /** RegularExpression Id. */
  int SINGLETON = 27;
  /** RegularExpression Id. */
  int BLOCK_START = 28;
  /** RegularExpression Id. */
  int BLOCK_END = 29;
  /** RegularExpression Id. */
  int SCRIPT_END = 30;
  /** RegularExpression Id. */
  int HTML_START = 31;
  /** RegularExpression Id. */
  int JSP_COMMENT_START = 32;
  /** RegularExpression Id. */
  int JSP_COMMENT = 33;
  /** RegularExpression Id. */
  int XML_COMMENT_START = 34;
  /** RegularExpression Id. */
  int XML_COMMENT = 35;
  /** RegularExpression Id. */
  int EMBEDD = 36;
  /** RegularExpression Id. */
  int SCRIPT = 37;
  /** RegularExpression Id. */
  int TAG_START = 38;
  /** RegularExpression Id. */
  int END_TAG = 39;
  /** RegularExpression Id. */
  int TAG_NAME = 40;
  /** RegularExpression Id. */
  int HTML_STOP = 41;
  /** RegularExpression Id. */
  int TEXT_CONTENT = 42;
  /** RegularExpression Id. */
  int WS = 43;
  /** RegularExpression Id. */
  int WS_OPT = 44;
  /** RegularExpression Id. */
  int TEXT_EMBEDD = 45;
  /** RegularExpression Id. */
  int PLAIN_TEXT = 46;
  /** RegularExpression Id. */
  int TAG_SPACE = 47;
  /** RegularExpression Id. */
  int TAG_TAB = 48;
  /** RegularExpression Id. */
  int TAG_CR = 49;
  /** RegularExpression Id. */
  int TAG_NL = 50;
  /** RegularExpression Id. */
  int ATTRIBUTE_NAME = 51;
  /** RegularExpression Id. */
  int EQ = 52;
  /** RegularExpression Id. */
  int QUOT_START = 53;
  /** RegularExpression Id. */
  int TAG_END = 54;
  /** RegularExpression Id. */
  int END_EMPTY_TAG = 55;
  /** RegularExpression Id. */
  int EMBEDD_ATTR = 56;
  /** RegularExpression Id. */
  int QUOT_END = 57;
  /** RegularExpression Id. */
  int ATTRIBUTE_TEXT = 58;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int HTML = 1;
  /** Lexical state. */
  int TEXT = 2;
  /** Lexical state. */
  int TAG = 3;
  /** Lexical state. */
  int ATTR_CONTENT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<BLOCK_COMMENT>",
    "<LINE_COMMENT>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<AND>",
    "<OR>",
    "\"this\"",
    "\"tuple\"",
    "\"switch\"",
    "\"default\"",
    "<NAME>",
    "<VAR>",
    "<STRING>",
    "<RESKEY>",
    "<LANGTAG>",
    "<QUOTE>",
    "<NUM>",
    "<MODEL_NAME>",
    "<MODULE>",
    "<TYPE>",
    "<PART>",
    "<SINGLETON>",
    "\"{\"",
    "\"}\"",
    "\"</script>\"",
    "\"{{{\"",
    "\"<%--\"",
    "<JSP_COMMENT>",
    "\"<!--\"",
    "<XML_COMMENT>",
    "\"{\"",
    "<SCRIPT>",
    "<TAG_START>",
    "<END_TAG>",
    "<TAG_NAME>",
    "\"}}}\"",
    "<TEXT_CONTENT>",
    "<WS>",
    "<WS_OPT>",
    "\"{\"",
    "<PLAIN_TEXT>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<ATTRIBUTE_NAME>",
    "\"=\"",
    "\"\\\"\"",
    "\">\"",
    "\"/>\"",
    "\"{\"",
    "\"\\\"\"",
    "<ATTRIBUTE_TEXT>",
    "\"->\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\">\"",
    "\"<=\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"=\"",
    "\"#(\"",
  };

}
