module.name = tl.react.flow.common
module.type = framework
module.scope = core
module.responsible = core

version.major = 7
version.minor = 11
version.micro = 0
version.qualifier = SNAPSHOT
version.patch =
build.id =
build.date =