/*
 * SPDX-FileCopyrightText: 2022 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.model.search.model.testJavaBinding.impl;

/**
 * Basic interface for {@link #ENUMS_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface EnumsBase extends test.com.top_logic.model.search.model.testJavaBinding.Common {

	/**
	 * Name of type <code>Enums</code>
	 */
	String ENUMS_TYPE = "Enums";

	/**
	 * Part <code>ref</code> of <code>Enums</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:E</code> in configuration.
	 * </p>
	 */
	String REF_ATTR = "ref";

	/**
	 * Part <code>refBag</code> of <code>Enums</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:E</code> in configuration.
	 * </p>
	 */
	String REF_BAG_ATTR = "refBag";

	/**
	 * Part <code>refMandatory</code> of <code>Enums</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:E</code> in configuration.
	 * </p>
	 */
	String REF_MANDATORY_ATTR = "refMandatory";

	/**
	 * Part <code>refMultiple</code> of <code>Enums</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:E</code> in configuration.
	 * </p>
	 */
	String REF_MULTIPLE_ATTR = "refMultiple";

	/**
	 * Part <code>refMultipleMandatory</code> of <code>Enums</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:E</code> in configuration.
	 * </p>
	 */
	String REF_MULTIPLE_MANDATORY_ATTR = "refMultipleMandatory";

	/**
	 * Part <code>refOrdered</code> of <code>Enums</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:E</code> in configuration.
	 * </p>
	 */
	String REF_ORDERED_ATTR = "refOrdered";

	/**
	 * Part <code>refOrderedBag</code> of <code>Enums</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:E</code> in configuration.
	 * </p>
	 */
	String REF_ORDERED_BAG_ATTR = "refOrderedBag";

	/**
	 * Getter for part {@link #REF_ATTR}.
	 */
	default com.top_logic.model.TLClassifier getRef() {
		return (com.top_logic.model.TLClassifier) tValueByName(REF_ATTR);
	}

	/**
	 * Setter for part {@link #REF_ATTR}.
	 */
	default void setRef(com.top_logic.model.TLClassifier newValue) {
		tUpdateByName(REF_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #REF_BAG_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Collection<com.top_logic.model.TLClassifier> getRefBag() {
		return (java.util.Collection<com.top_logic.model.TLClassifier>) tValueByName(REF_BAG_ATTR);
	}

	/**
	 * Live view of the {@link #REF_BAG_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Collection<com.top_logic.model.TLClassifier> getRefBagModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(REF_BAG_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Collection<com.top_logic.model.TLClassifier> result = (java.util.Collection<com.top_logic.model.TLClassifier>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #REF_BAG_ATTR}.
	 */
	default void setRefBag(java.util.Collection<com.top_logic.model.TLClassifier> newValue) {
		tUpdateByName(REF_BAG_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #REF_BAG_ATTR} reference.
	 */
	default void addRefBag(com.top_logic.model.TLClassifier newValue) {
		tAddByName(REF_BAG_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #REF_BAG_ATTR} reference.
	 */
	default void removeRefBag(com.top_logic.model.TLClassifier oldValue) {
		tRemoveByName(REF_BAG_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #REF_MANDATORY_ATTR}.
	 */
	default com.top_logic.model.TLClassifier getRefMandatory() {
		return (com.top_logic.model.TLClassifier) tValueByName(REF_MANDATORY_ATTR);
	}

	/**
	 * Setter for part {@link #REF_MANDATORY_ATTR}.
	 */
	default void setRefMandatory(com.top_logic.model.TLClassifier newValue) {
		tUpdateByName(REF_MANDATORY_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #REF_MULTIPLE_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<com.top_logic.model.TLClassifier> getRefMultiple() {
		return (java.util.Set<com.top_logic.model.TLClassifier>) tValueByName(REF_MULTIPLE_ATTR);
	}

	/**
	 * Live view of the {@link #REF_MULTIPLE_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<com.top_logic.model.TLClassifier> getRefMultipleModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(REF_MULTIPLE_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<com.top_logic.model.TLClassifier> result = (java.util.Set<com.top_logic.model.TLClassifier>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #REF_MULTIPLE_ATTR}.
	 */
	default void setRefMultiple(java.util.Set<com.top_logic.model.TLClassifier> newValue) {
		tUpdateByName(REF_MULTIPLE_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #REF_MULTIPLE_ATTR} reference.
	 */
	default void addRefMultiple(com.top_logic.model.TLClassifier newValue) {
		tAddByName(REF_MULTIPLE_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #REF_MULTIPLE_ATTR} reference.
	 */
	default void removeRefMultiple(com.top_logic.model.TLClassifier oldValue) {
		tRemoveByName(REF_MULTIPLE_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #REF_MULTIPLE_MANDATORY_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<com.top_logic.model.TLClassifier> getRefMultipleMandatory() {
		return (java.util.Set<com.top_logic.model.TLClassifier>) tValueByName(REF_MULTIPLE_MANDATORY_ATTR);
	}

	/**
	 * Live view of the {@link #REF_MULTIPLE_MANDATORY_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<com.top_logic.model.TLClassifier> getRefMultipleMandatoryModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(REF_MULTIPLE_MANDATORY_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<com.top_logic.model.TLClassifier> result = (java.util.Set<com.top_logic.model.TLClassifier>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #REF_MULTIPLE_MANDATORY_ATTR}.
	 */
	default void setRefMultipleMandatory(java.util.Set<com.top_logic.model.TLClassifier> newValue) {
		tUpdateByName(REF_MULTIPLE_MANDATORY_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #REF_MULTIPLE_MANDATORY_ATTR} reference.
	 */
	default void addRefMultipleMandatory(com.top_logic.model.TLClassifier newValue) {
		tAddByName(REF_MULTIPLE_MANDATORY_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #REF_MULTIPLE_MANDATORY_ATTR} reference.
	 */
	default void removeRefMultipleMandatory(com.top_logic.model.TLClassifier oldValue) {
		tRemoveByName(REF_MULTIPLE_MANDATORY_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #REF_ORDERED_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.List<com.top_logic.model.TLClassifier> getRefOrdered() {
		return (java.util.List<com.top_logic.model.TLClassifier>) tValueByName(REF_ORDERED_ATTR);
	}

	/**
	 * Live view of the {@link #REF_ORDERED_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.List<com.top_logic.model.TLClassifier> getRefOrderedModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(REF_ORDERED_ATTR);
		@SuppressWarnings("unchecked")
		java.util.List<com.top_logic.model.TLClassifier> result = (java.util.List<com.top_logic.model.TLClassifier>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #REF_ORDERED_ATTR}.
	 */
	default void setRefOrdered(java.util.List<com.top_logic.model.TLClassifier> newValue) {
		tUpdateByName(REF_ORDERED_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #REF_ORDERED_ATTR} reference.
	 */
	default void addRefOrdered(com.top_logic.model.TLClassifier newValue) {
		tAddByName(REF_ORDERED_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #REF_ORDERED_ATTR} reference.
	 */
	default void removeRefOrdered(com.top_logic.model.TLClassifier oldValue) {
		tRemoveByName(REF_ORDERED_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #REF_ORDERED_BAG_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.List<com.top_logic.model.TLClassifier> getRefOrderedBag() {
		return (java.util.List<com.top_logic.model.TLClassifier>) tValueByName(REF_ORDERED_BAG_ATTR);
	}

	/**
	 * Live view of the {@link #REF_ORDERED_BAG_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.List<com.top_logic.model.TLClassifier> getRefOrderedBagModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(REF_ORDERED_BAG_ATTR);
		@SuppressWarnings("unchecked")
		java.util.List<com.top_logic.model.TLClassifier> result = (java.util.List<com.top_logic.model.TLClassifier>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #REF_ORDERED_BAG_ATTR}.
	 */
	default void setRefOrderedBag(java.util.List<com.top_logic.model.TLClassifier> newValue) {
		tUpdateByName(REF_ORDERED_BAG_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #REF_ORDERED_BAG_ATTR} reference.
	 */
	default void addRefOrderedBag(com.top_logic.model.TLClassifier newValue) {
		tAddByName(REF_ORDERED_BAG_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #REF_ORDERED_BAG_ATTR} reference.
	 */
	default void removeRefOrderedBag(com.top_logic.model.TLClassifier oldValue) {
		tRemoveByName(REF_ORDERED_BAG_ATTR, oldValue);
	}

}
