/*
 * SPDX-FileCopyrightText: 2022 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.model.search.model.testJavaBinding.impl;

import com.top_logic.knowledge.objects.KnowledgeObject;

/**
 * Wrapper implementation class for <code>TestJavaBinding:Enums</code> business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.ImplementationTemplateGenerator}
 */
public class EnumsImpl extends CommonImpl implements test.com.top_logic.model.search.model.testJavaBinding.Enums {

	/**
	 * Default constructor.
	 */
	public EnumsImpl(KnowledgeObject ko) {
		super(ko);
	}

}
