/*
 * SPDX-FileCopyrightText: 2022 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.model.search.model.testJavaBinding.impl;

/**
 * Basic interface for {@link #PRIMITIVES_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface PrimitivesBase extends test.com.top_logic.model.search.model.testJavaBinding.Common {

	/**
	 * Name of type <code>Primitives</code>
	 */
	String PRIMITIVES_TYPE = "Primitives";

	/**
	 * Part <code>byte</code> of <code>Primitives</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Byte</code> in configuration.
	 * </p>
	 */
	String BYTE_ATTR = "byte";

	/**
	 * Part <code>double</code> of <code>Primitives</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Double</code> in configuration.
	 * </p>
	 */
	String DOUBLE_ATTR = "double";

	/**
	 * Part <code>float</code> of <code>Primitives</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Float</code> in configuration.
	 * </p>
	 */
	String FLOAT_ATTR = "float";

	/**
	 * Part <code>int</code> of <code>Primitives</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Integer</code> in configuration.
	 * </p>
	 */
	String INT_ATTR = "int";

	/**
	 * Part <code>long</code> of <code>Primitives</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Long</code> in configuration.
	 * </p>
	 */
	String LONG_ATTR = "long";

	/**
	 * Part <code>short</code> of <code>Primitives</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Short</code> in configuration.
	 * </p>
	 */
	String SHORT_ATTR = "short";

	/**
	 * Getter for part {@link #BYTE_ATTR}.
	 */
	default Integer getByte() {
		return (Integer) tValueByName(BYTE_ATTR);
	}

	/**
	 * Setter for part {@link #BYTE_ATTR}.
	 */
	default void setByte(Integer newValue) {
		tUpdateByName(BYTE_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #DOUBLE_ATTR}.
	 */
	default Double getDouble() {
		return (Double) tValueByName(DOUBLE_ATTR);
	}

	/**
	 * Setter for part {@link #DOUBLE_ATTR}.
	 */
	default void setDouble(Double newValue) {
		tUpdateByName(DOUBLE_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #FLOAT_ATTR}.
	 */
	default Float getFloat() {
		return (Float) tValueByName(FLOAT_ATTR);
	}

	/**
	 * Setter for part {@link #FLOAT_ATTR}.
	 */
	default void setFloat(Float newValue) {
		tUpdateByName(FLOAT_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #INT_ATTR}.
	 */
	default Integer getInt() {
		return (Integer) tValueByName(INT_ATTR);
	}

	/**
	 * Setter for part {@link #INT_ATTR}.
	 */
	default void setInt(Integer newValue) {
		tUpdateByName(INT_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #LONG_ATTR}.
	 */
	default Long getLong() {
		return (Long) tValueByName(LONG_ATTR);
	}

	/**
	 * Setter for part {@link #LONG_ATTR}.
	 */
	default void setLong(Long newValue) {
		tUpdateByName(LONG_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #SHORT_ATTR}.
	 */
	default Integer getShort() {
		return (Integer) tValueByName(SHORT_ATTR);
	}

	/**
	 * Setter for part {@link #SHORT_ATTR}.
	 */
	default void setShort(Integer newValue) {
		tUpdateByName(SHORT_ATTR, newValue);
	}

}
