/*
 * SPDX-FileCopyrightText: 2022 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.model.search.model.testJavaBinding.impl;

/**
 * Basic interface for {@link #REFERENCES_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ReferencesBase extends test.com.top_logic.model.search.model.testJavaBinding.Common {

	/**
	 * Name of type <code>References</code>
	 */
	String REFERENCES_TYPE = "References";

	/**
	 * Part <code>ref</code> of <code>References</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:Primitives</code> in configuration.
	 * </p>
	 */
	String REF_ATTR = "ref";

	/**
	 * Part <code>refBag</code> of <code>References</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:Primitives</code> in configuration.
	 * </p>
	 */
	String REF_BAG_ATTR = "refBag";

	/**
	 * Part <code>refMandatory</code> of <code>References</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:Primitives</code> in configuration.
	 * </p>
	 */
	String REF_MANDATORY_ATTR = "refMandatory";

	/**
	 * Part <code>refMultiple</code> of <code>References</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:Primitives</code> in configuration.
	 * </p>
	 */
	String REF_MULTIPLE_ATTR = "refMultiple";

	/**
	 * Part <code>refMultipleMandatory</code> of <code>References</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:Primitives</code> in configuration.
	 * </p>
	 */
	String REF_MULTIPLE_MANDATORY_ATTR = "refMultipleMandatory";

	/**
	 * Part <code>refOrdered</code> of <code>References</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:Primitives</code> in configuration.
	 * </p>
	 */
	String REF_ORDERED_ATTR = "refOrdered";

	/**
	 * Part <code>refOrderedBag</code> of <code>References</code>
	 * 
	 * <p>
	 * Declared as <code>TestJavaBinding:Primitives</code> in configuration.
	 * </p>
	 */
	String REF_ORDERED_BAG_ATTR = "refOrderedBag";

	/**
	 * Getter for part {@link #REF_ATTR}.
	 */
	default test.com.top_logic.model.search.model.testJavaBinding.Primitives getRef() {
		return (test.com.top_logic.model.search.model.testJavaBinding.Primitives) tValueByName(REF_ATTR);
	}

	/**
	 * Setter for part {@link #REF_ATTR}.
	 */
	default void setRef(test.com.top_logic.model.search.model.testJavaBinding.Primitives newValue) {
		tUpdateByName(REF_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #REF_BAG_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Collection<? extends test.com.top_logic.model.search.model.testJavaBinding.Primitives> getRefBag() {
		return (java.util.Collection<? extends test.com.top_logic.model.search.model.testJavaBinding.Primitives>) tValueByName(REF_BAG_ATTR);
	}

	/**
	 * Live view of the {@link #REF_BAG_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Collection<test.com.top_logic.model.search.model.testJavaBinding.Primitives> getRefBagModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(REF_BAG_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Collection<test.com.top_logic.model.search.model.testJavaBinding.Primitives> result = (java.util.Collection<test.com.top_logic.model.search.model.testJavaBinding.Primitives>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #REF_BAG_ATTR}.
	 */
	default void setRefBag(java.util.Collection<test.com.top_logic.model.search.model.testJavaBinding.Primitives> newValue) {
		tUpdateByName(REF_BAG_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #REF_BAG_ATTR} reference.
	 */
	default void addRefBag(test.com.top_logic.model.search.model.testJavaBinding.Primitives newValue) {
		tAddByName(REF_BAG_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #REF_BAG_ATTR} reference.
	 */
	default void removeRefBag(test.com.top_logic.model.search.model.testJavaBinding.Primitives oldValue) {
		tRemoveByName(REF_BAG_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #REF_MANDATORY_ATTR}.
	 */
	default test.com.top_logic.model.search.model.testJavaBinding.Primitives getRefMandatory() {
		return (test.com.top_logic.model.search.model.testJavaBinding.Primitives) tValueByName(REF_MANDATORY_ATTR);
	}

	/**
	 * Setter for part {@link #REF_MANDATORY_ATTR}.
	 */
	default void setRefMandatory(test.com.top_logic.model.search.model.testJavaBinding.Primitives newValue) {
		tUpdateByName(REF_MANDATORY_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #REF_MULTIPLE_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends test.com.top_logic.model.search.model.testJavaBinding.Primitives> getRefMultiple() {
		return (java.util.Set<? extends test.com.top_logic.model.search.model.testJavaBinding.Primitives>) tValueByName(REF_MULTIPLE_ATTR);
	}

	/**
	 * Live view of the {@link #REF_MULTIPLE_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<test.com.top_logic.model.search.model.testJavaBinding.Primitives> getRefMultipleModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(REF_MULTIPLE_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<test.com.top_logic.model.search.model.testJavaBinding.Primitives> result = (java.util.Set<test.com.top_logic.model.search.model.testJavaBinding.Primitives>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #REF_MULTIPLE_ATTR}.
	 */
	default void setRefMultiple(java.util.Set<test.com.top_logic.model.search.model.testJavaBinding.Primitives> newValue) {
		tUpdateByName(REF_MULTIPLE_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #REF_MULTIPLE_ATTR} reference.
	 */
	default void addRefMultiple(test.com.top_logic.model.search.model.testJavaBinding.Primitives newValue) {
		tAddByName(REF_MULTIPLE_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #REF_MULTIPLE_ATTR} reference.
	 */
	default void removeRefMultiple(test.com.top_logic.model.search.model.testJavaBinding.Primitives oldValue) {
		tRemoveByName(REF_MULTIPLE_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #REF_MULTIPLE_MANDATORY_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends test.com.top_logic.model.search.model.testJavaBinding.Primitives> getRefMultipleMandatory() {
		return (java.util.Set<? extends test.com.top_logic.model.search.model.testJavaBinding.Primitives>) tValueByName(REF_MULTIPLE_MANDATORY_ATTR);
	}

	/**
	 * Live view of the {@link #REF_MULTIPLE_MANDATORY_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<test.com.top_logic.model.search.model.testJavaBinding.Primitives> getRefMultipleMandatoryModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(REF_MULTIPLE_MANDATORY_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<test.com.top_logic.model.search.model.testJavaBinding.Primitives> result = (java.util.Set<test.com.top_logic.model.search.model.testJavaBinding.Primitives>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #REF_MULTIPLE_MANDATORY_ATTR}.
	 */
	default void setRefMultipleMandatory(java.util.Set<test.com.top_logic.model.search.model.testJavaBinding.Primitives> newValue) {
		tUpdateByName(REF_MULTIPLE_MANDATORY_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #REF_MULTIPLE_MANDATORY_ATTR} reference.
	 */
	default void addRefMultipleMandatory(test.com.top_logic.model.search.model.testJavaBinding.Primitives newValue) {
		tAddByName(REF_MULTIPLE_MANDATORY_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #REF_MULTIPLE_MANDATORY_ATTR} reference.
	 */
	default void removeRefMultipleMandatory(test.com.top_logic.model.search.model.testJavaBinding.Primitives oldValue) {
		tRemoveByName(REF_MULTIPLE_MANDATORY_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #REF_ORDERED_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.List<? extends test.com.top_logic.model.search.model.testJavaBinding.Primitives> getRefOrdered() {
		return (java.util.List<? extends test.com.top_logic.model.search.model.testJavaBinding.Primitives>) tValueByName(REF_ORDERED_ATTR);
	}

	/**
	 * Live view of the {@link #REF_ORDERED_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.List<test.com.top_logic.model.search.model.testJavaBinding.Primitives> getRefOrderedModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(REF_ORDERED_ATTR);
		@SuppressWarnings("unchecked")
		java.util.List<test.com.top_logic.model.search.model.testJavaBinding.Primitives> result = (java.util.List<test.com.top_logic.model.search.model.testJavaBinding.Primitives>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #REF_ORDERED_ATTR}.
	 */
	default void setRefOrdered(java.util.List<test.com.top_logic.model.search.model.testJavaBinding.Primitives> newValue) {
		tUpdateByName(REF_ORDERED_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #REF_ORDERED_ATTR} reference.
	 */
	default void addRefOrdered(test.com.top_logic.model.search.model.testJavaBinding.Primitives newValue) {
		tAddByName(REF_ORDERED_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #REF_ORDERED_ATTR} reference.
	 */
	default void removeRefOrdered(test.com.top_logic.model.search.model.testJavaBinding.Primitives oldValue) {
		tRemoveByName(REF_ORDERED_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #REF_ORDERED_BAG_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.List<? extends test.com.top_logic.model.search.model.testJavaBinding.Primitives> getRefOrderedBag() {
		return (java.util.List<? extends test.com.top_logic.model.search.model.testJavaBinding.Primitives>) tValueByName(REF_ORDERED_BAG_ATTR);
	}

	/**
	 * Live view of the {@link #REF_ORDERED_BAG_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.List<test.com.top_logic.model.search.model.testJavaBinding.Primitives> getRefOrderedBagModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(REF_ORDERED_BAG_ATTR);
		@SuppressWarnings("unchecked")
		java.util.List<test.com.top_logic.model.search.model.testJavaBinding.Primitives> result = (java.util.List<test.com.top_logic.model.search.model.testJavaBinding.Primitives>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #REF_ORDERED_BAG_ATTR}.
	 */
	default void setRefOrderedBag(java.util.List<test.com.top_logic.model.search.model.testJavaBinding.Primitives> newValue) {
		tUpdateByName(REF_ORDERED_BAG_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #REF_ORDERED_BAG_ATTR} reference.
	 */
	default void addRefOrderedBag(test.com.top_logic.model.search.model.testJavaBinding.Primitives newValue) {
		tAddByName(REF_ORDERED_BAG_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #REF_ORDERED_BAG_ATTR} reference.
	 */
	default void removeRefOrderedBag(test.com.top_logic.model.search.model.testJavaBinding.Primitives oldValue) {
		tRemoveByName(REF_ORDERED_BAG_ATTR, oldValue);
	}

}
