/*
 * SPDX-FileCopyrightText: 2026 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.security.selfservice.model.impl;

/**
 * Basic interface for {@link #INVITATION_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface InvitationBase extends com.top_logic.model.TLObject {

	/**
	 * Name of type <code>Invitation</code>
	 */
	String INVITATION_TYPE = "Invitation";

	/**
	 * Part <code>email</code> of <code>Invitation</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String EMAIL_ATTR = "email";

	/**
	 * Part <code>id</code> of <code>Invitation</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String ID_ATTR = "id";

	/**
	 * Part <code>token</code> of <code>Invitation</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Password</code> in configuration.
	 * </p>
	 */
	String TOKEN_ATTR = "token";

	/**
	 * Part <code>tokenCounter</code> of <code>Invitation</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Integer</code> in configuration.
	 * </p>
	 */
	String TOKEN_COUNTER_ATTR = "tokenCounter";

	/**
	 * Part <code>tokenCreation</code> of <code>Invitation</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Long</code> in configuration.
	 * </p>
	 */
	String TOKEN_CREATION_ATTR = "tokenCreation";

	/**
	 * Part <code>tokenMismatchCounter</code> of <code>Invitation</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Integer</code> in configuration.
	 * </p>
	 */
	String TOKEN_MISMATCH_COUNTER_ATTR = "tokenMismatchCounter";

	/**
	 * Getter for part {@link #EMAIL_ATTR}.
	 */
	default String getEmail() {
		return (String) tValueByName(EMAIL_ATTR);
	}

	/**
	 * Setter for part {@link #EMAIL_ATTR}.
	 */
	default void setEmail(String newValue) {
		tUpdateByName(EMAIL_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #ID_ATTR}.
	 */
	default String getId() {
		return (String) tValueByName(ID_ATTR);
	}

	/**
	 * Setter for part {@link #ID_ATTR}.
	 */
	default void setId(String newValue) {
		tUpdateByName(ID_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #TOKEN_ATTR}.
	 */
	default com.top_logic.base.security.util.Password getToken() {
		return (com.top_logic.base.security.util.Password) tValueByName(TOKEN_ATTR);
	}

	/**
	 * Setter for part {@link #TOKEN_ATTR}.
	 */
	default void setToken(com.top_logic.base.security.util.Password newValue) {
		tUpdateByName(TOKEN_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #TOKEN_COUNTER_ATTR}.
	 */
	default int getTokenCounter() {
		return (Integer) tValueByName(TOKEN_COUNTER_ATTR);
	}

	/**
	 * Setter for part {@link #TOKEN_COUNTER_ATTR}.
	 */
	default void setTokenCounter(int newValue) {
		tUpdateByName(TOKEN_COUNTER_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #TOKEN_CREATION_ATTR}.
	 */
	default Long getTokenCreation() {
		return (Long) tValueByName(TOKEN_CREATION_ATTR);
	}

	/**
	 * Setter for part {@link #TOKEN_CREATION_ATTR}.
	 */
	default void setTokenCreation(Long newValue) {
		tUpdateByName(TOKEN_CREATION_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #TOKEN_MISMATCH_COUNTER_ATTR}.
	 */
	default int getTokenMismatchCounter() {
		return (Integer) tValueByName(TOKEN_MISMATCH_COUNTER_ATTR);
	}

	/**
	 * Setter for part {@link #TOKEN_MISMATCH_COUNTER_ATTR}.
	 */
	default void setTokenMismatchCounter(int newValue) {
		tUpdateByName(TOKEN_MISMATCH_COUNTER_ATTR, newValue);
	}

}
