ALTER TABLE TL_USER 
   MODIFY COLUMN CN           CHAR(128)    NOT NULL,
   MODIFY COLUMN GIVEN_NAME   VARCHAR(128) NOT NULL,
   MODIFY COLUMN SN           VARCHAR(128) NULL,
   MODIFY COLUMN DISPLAY_NAME VARCHAR(512) NULL;
