DROP TABLE CA_COLS;
DROP SEQUENCE SEQ_CA_COLS;

DROP TABLE CA_CONTENT;
DROP SEQUENCE SEQ_CA_CONTENT;

DROP TABLE CA_CONTENT_COLLECTION;
DROP SEQUENCE SEQ_CA_CONTENT_COLLECTION;

DROP TABLE CA_ELEMENT;
DROP SEQUENCE SEQ_CA_ELEMENT;

DROP TABLE CA_ITEMS;
DROP SEQUENCE SEQ_CA_ITEMS;

DROP TABLE CA_REVISION;
DROP SEQUENCE SEQ_CA_REVISION;

DROP TABLE CA_ROWS;
DROP SEQUENCE SEQ_CA_ROWS;
