DROP TABLE IF EXISTS CA_COLS;
DROP TABLE IF EXISTS CA_CONTENT;
DROP TABLE IF EXISTS CA_CONTENT_COLLECTION;
DROP TABLE IF EXISTS CA_ELEMENT;
DROP TABLE IF EXISTS CA_ITEMS;
DROP TABLE IF EXISTS CA_REVISION;
DROP TABLE IF EXISTS CA_ROWS;