/*
 * SPDX-FileCopyrightText: 2026 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.element.model.accounts.impl;

/**
 * Basic interface for {@link #GROUP_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface GroupBase extends com.top_logic.element.model.accounts.GroupMember, com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>Group</code>
	 */
	String GROUP_TYPE = "Group";

	/**
	 * Part <code>defaultGroup</code> of <code>Group</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Boolean</code> in configuration.
	 * </p>
	 */
	String DEFAULT_GROUP_ATTR = "defaultGroup";

	/**
	 * Part <code>isSystem</code> of <code>Group</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Boolean</code> in configuration.
	 * </p>
	 */
	String IS_SYSTEM_ATTR = "isSystem";

	/**
	 * Part <code>members</code> of <code>Group</code>
	 * 
	 * <p>
	 * Declared as <code>tl.accounts:GroupMember</code> in configuration.
	 * </p>
	 */
	String MEMBERS_ATTR = "members";

	/**
	 * Part <code>name</code> of <code>Group</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

}
