/*
 * SPDX-FileCopyrightText: 2026 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.element.model.accounts.impl;

/**
 * Basic interface for {@link #REPRESENTATIVE_GROUP_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface RepresentativeGroupBase extends com.top_logic.element.model.accounts.Group {

	/**
	 * Name of type <code>RepresentativeGroup</code>
	 */
	String REPRESENTATIVE_GROUP_TYPE = "RepresentativeGroup";

}
