/*
 * SPDX-FileCopyrightText: 2009 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.template.tree;

import java.util.Map;

/**
 * Represents an for-each {@link FunctionStatement} in the template language.
 * 
 * @author <a href=mailto:tbe@top-logic.com>tbe</a>
 */
public class ForeachStatement extends FunctionStatement {

	private final String              variable;
	private final Expression          expression;
	private final Map<String, String> attributes;
	private final TemplateNode        innerNode;

	/**
	 * Creates a new {@link ForeachStatement}.
	 */
	public ForeachStatement(String varName, Expression expression, Map < String, String > attributes, TemplateNode innerNode) {
		this.variable   = varName;
		this.expression = expression;
		this.attributes = attributes;
		this.innerNode  = innerNode;
		
	}
	
	@Override
	public Map<String, String> getAttributes() {
		return this.attributes;
	}

	@Override
	public <R, A> R visit(TemplateVisitor<R, A> v, A arg) {
		return v.visitForeachStatement(this, arg);
	}

	/**
	 * the {@link TemplateNode} that will be generated for each object generated by the
	 *         expression.
	 */
	public final TemplateNode getProductionNode() {
		return this.innerNode;
	}

	/**
	 * the name of the variable that will be used for the assignments.
	 */
	public final String getVariable() {
		return variable;
	}

	/**
	 * Returns the {@link Expression} used for this ForeachStm.
	 */
	public Expression getExpression() {
		return expression;
	}
}