/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.element.meta.model.ticket28519.impl;

import com.top_logic.knowledge.objects.KnowledgeObject;

/**
 * Wrapper implementation class for <code>ticket28519:B2</code> business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.ImplementationTemplateGenerator}
 */
public class B2Impl extends com.top_logic.element.meta.kbbased.AttributedWrapper implements test.com.top_logic.element.meta.model.ticket28519.B2 {

	/**
	 * Default constructor.
	 */
	public B2Impl(KnowledgeObject ko) {
		super(ko);
	}

}
