/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.bpe.bpml.model.impl;

/**
 * Basic interface for {@link #ANNOTATION_ASSOCIATION_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface AnnotationAssociationBase extends com.top_logic.bpe.bpml.model.Externalized {

	/**
	 * Name of type <code>AnnotationAssociation</code>
	 */
	String ANNOTATION_ASSOCIATION_TYPE = "AnnotationAssociation";

	/**
	 * Part <code>source</code> of <code>AnnotationAssociation</code>
	 * 
	 * <p>
	 * Declared as <code>tl.bpe.bpml:Annotated</code> in configuration.
	 * </p>
	 */
	String SOURCE_ATTR = "source";

	/**
	 * Part <code>target</code> of <code>AnnotationAssociation</code>
	 * 
	 * <p>
	 * Declared as <code>tl.bpe.bpml:TextAnnotation</code> in configuration.
	 * </p>
	 */
	String TARGET_ATTR = "target";

	/**
	 * Getter for part {@link #SOURCE_ATTR}.
	 */
	default com.top_logic.bpe.bpml.model.Annotated getSource() {
		return (com.top_logic.bpe.bpml.model.Annotated) tValueByName(SOURCE_ATTR);
	}

	/**
	 * Setter for part {@link #SOURCE_ATTR}.
	 */
	default void setSource(com.top_logic.bpe.bpml.model.Annotated newValue) {
		tUpdateByName(SOURCE_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #TARGET_ATTR}.
	 */
	default com.top_logic.bpe.bpml.model.TextAnnotation getTarget() {
		return (com.top_logic.bpe.bpml.model.TextAnnotation) tValueByName(TARGET_ATTR);
	}

	/**
	 * Setter for part {@link #TARGET_ATTR}.
	 */
	default void setTarget(com.top_logic.bpe.bpml.model.TextAnnotation newValue) {
		tUpdateByName(TARGET_ATTR, newValue);
	}

}
