/*
 * SPDX-FileCopyrightText: 2022 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.bpe.bpml.model.impl;

/**
 * Basic interface for {@link #ANNOTATED_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface AnnotatedBase extends com.top_logic.bpe.bpml.model.Externalized {

	/**
	 * Name of type <code>Annotated</code>
	 */
	String ANNOTATED_TYPE = "Annotated";

	/**
	 * Part <code>annotationAssociations</code> of <code>Annotated</code>
	 * 
	 * <p>
	 * Declared as <code>tl.bpe.bpml:AnnotationAssociation</code> in configuration.
	 * </p>
	 */
	String ANNOTATION_ASSOCIATIONS_ATTR = "annotationAssociations";

	/**
	 * Getter for part {@link #ANNOTATION_ASSOCIATIONS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.bpe.bpml.model.AnnotationAssociation> getAnnotationAssociations() {
		return (java.util.Set<? extends com.top_logic.bpe.bpml.model.AnnotationAssociation>) tValueByName(ANNOTATION_ASSOCIATIONS_ATTR);
	}

}
