/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.bpe.bpml.model.impl;

/**
 * Basic interface for {@link #END_EVENT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface EndEventBase extends com.top_logic.bpe.bpml.model.Event, com.top_logic.bpe.bpml.model.FlowSource {

	/**
	 * Name of type <code>EndEvent</code>
	 */
	String END_EVENT_TYPE = "EndEvent";

}
