/*
 * SPDX-FileCopyrightText: 2022 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.bpe.bpml.model.impl;

/**
 * Basic interface for {@link #INCLUSIVE_GATEWAY_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface InclusiveGatewayBase extends com.top_logic.bpe.bpml.model.DefaultGateway {

	/**
	 * Name of type <code>InclusiveGateway</code>
	 */
	String INCLUSIVE_GATEWAY_TYPE = "InclusiveGateway";

}
