/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.bpe.bpml.model.impl;

/**
 * Basic interface for {@link #MANUAL_TASK_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ManualTaskBase extends com.top_logic.bpe.bpml.model.Task {

	/**
	 * Name of type <code>ManualTask</code>
	 */
	String MANUAL_TASK_TYPE = "ManualTask";

	/**
	 * Part <code>formDefinition</code> of <code>ManualTask</code>
	 * 
	 * <p>
	 * Declared as <code>tl.bpe.bpml:ProcessFormDefinition</code> in configuration.
	 * </p>
	 */
	String FORM_DEFINITION_ATTR = "formDefinition";

	/**
	 * Getter for part {@link #FORM_DEFINITION_ATTR}.
	 */
	default com.top_logic.bpe.bpml.display.ProcessFormDefinition getFormDefinition() {
		return (com.top_logic.bpe.bpml.display.ProcessFormDefinition) tValueByName(FORM_DEFINITION_ATTR);
	}

	/**
	 * Setter for part {@link #FORM_DEFINITION_ATTR}.
	 */
	default void setFormDefinition(com.top_logic.bpe.bpml.display.ProcessFormDefinition newValue) {
		tUpdateByName(FORM_DEFINITION_ATTR, newValue);
	}

}
