/*
 * SPDX-FileCopyrightText: 2022 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.bpe.bpml.model.impl;

import com.top_logic.knowledge.objects.KnowledgeObject;

/**
 * Wrapper implementation class for <code>tl.bpe.bpml:MessageFlow</code> business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.ImplementationTemplateGenerator}
 */
public class MessageFlowImpl extends com.top_logic.element.meta.kbbased.AttributedWrapper implements com.top_logic.bpe.bpml.model.MessageFlow {

	/**
	 * Default constructor.
	 */
	public MessageFlowImpl(KnowledgeObject ko) {
		super(ko);
	}

}
