/*
 * SPDX-FileCopyrightText: 2022 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.bpe.bpml.model.impl;

/**
 * Basic interface for {@link #PARALLEL_GATEWAY_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ParallelGatewayBase extends com.top_logic.bpe.bpml.model.Gateway {

	/**
	 * Name of type <code>ParallelGateway</code>
	 */
	String PARALLEL_GATEWAY_TYPE = "ParallelGateway";

}
