/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.bpe.bpml.model.impl;

/**
 * Basic interface for {@link #PARTICIPANT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ParticipantBase extends com.top_logic.bpe.bpml.model.Named, com.top_logic.bpe.bpml.model.FlowSource, com.top_logic.bpe.bpml.model.FlowTarget, com.top_logic.bpe.bpml.model.Annotated {

	/**
	 * Name of type <code>Participant</code>
	 */
	String PARTICIPANT_TYPE = "Participant";

	/**
	 * Part <code>collaboration</code> of <code>Participant</code>
	 * 
	 * <p>
	 * Declared as <code>tl.bpe.bpml:Collaboration</code> in configuration.
	 * </p>
	 */
	String COLLABORATION_ATTR = "collaboration";

	/**
	 * Part <code>defaultOperation</code> of <code>Participant</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model.search:Expr</code> in configuration.
	 * </p>
	 */
	String DEFAULT_OPERATION_ATTR = "defaultOperation";

	/**
	 * Part <code>displayDescription</code> of <code>Participant</code>
	 * 
	 * <p>
	 * Declared as <code>tl.bpe.bpml:DisplayDescription</code> in configuration.
	 * </p>
	 */
	String DISPLAY_DESCRIPTION_ATTR = "displayDescription";

	/**
	 * Part <code>dynamicName</code> of <code>Participant</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model.search:Expr</code> in configuration.
	 * </p>
	 */
	String DYNAMIC_NAME_ATTR = "dynamicName";

	/**
	 * Part <code>edgeFormType</code> of <code>Participant</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model:TLClass</code> in configuration.
	 * </p>
	 */
	String EDGE_FORM_TYPE_ATTR = "edgeFormType";

	/**
	 * Part <code>exportDescription</code> of <code>Participant</code>
	 * 
	 * <p>
	 * Declared as <code>tl.bpe.bpml:DisplayDescription</code> in configuration.
	 * </p>
	 */
	String EXPORT_DESCRIPTION_ATTR = "exportDescription";

	/**
	 * Part <code>modelType</code> of <code>Participant</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model:TLClass</code> in configuration.
	 * </p>
	 */
	String MODEL_TYPE_ATTR = "modelType";

	/**
	 * Part <code>process</code> of <code>Participant</code>
	 * 
	 * <p>
	 * Declared as <code>tl.bpe.bpml:Process</code> in configuration.
	 * </p>
	 */
	String PROCESS_ATTR = "process";

	/**
	 * Part <code>taskLabel</code> of <code>Participant</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model.search:Expr</code> in configuration.
	 * </p>
	 */
	String TASK_LABEL_ATTR = "taskLabel";

	/**
	 * Part <code>tokenType</code> of <code>Participant</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model:TLClass</code> in configuration.
	 * </p>
	 */
	String TOKEN_TYPE_ATTR = "tokenType";

	/**
	 * Getter for part {@link #COLLABORATION_ATTR}.
	 */
	default com.top_logic.bpe.bpml.model.Collaboration getCollaboration() {
		return (com.top_logic.bpe.bpml.model.Collaboration) tValueByName(COLLABORATION_ATTR);
	}

	/**
	 * Getter for part {@link #DEFAULT_OPERATION_ATTR}.
	 */
	default com.top_logic.model.search.expr.SearchExpression getDefaultOperation() {
		return (com.top_logic.model.search.expr.SearchExpression) tValueByName(DEFAULT_OPERATION_ATTR);
	}

	/**
	 * Setter for part {@link #DEFAULT_OPERATION_ATTR}.
	 */
	default void setDefaultOperation(com.top_logic.model.search.expr.SearchExpression newValue) {
		tUpdateByName(DEFAULT_OPERATION_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #DISPLAY_DESCRIPTION_ATTR}.
	 */
	default com.top_logic.model.form.definition.FormDefinition getDisplayDescription() {
		return (com.top_logic.model.form.definition.FormDefinition) tValueByName(DISPLAY_DESCRIPTION_ATTR);
	}

	/**
	 * Setter for part {@link #DISPLAY_DESCRIPTION_ATTR}.
	 */
	default void setDisplayDescription(com.top_logic.model.form.definition.FormDefinition newValue) {
		tUpdateByName(DISPLAY_DESCRIPTION_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #DYNAMIC_NAME_ATTR}.
	 */
	default com.top_logic.model.search.expr.SearchExpression getDynamicName() {
		return (com.top_logic.model.search.expr.SearchExpression) tValueByName(DYNAMIC_NAME_ATTR);
	}

	/**
	 * Setter for part {@link #DYNAMIC_NAME_ATTR}.
	 */
	default void setDynamicName(com.top_logic.model.search.expr.SearchExpression newValue) {
		tUpdateByName(DYNAMIC_NAME_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #EDGE_FORM_TYPE_ATTR}.
	 */
	default com.top_logic.model.TLClass getEdgeFormType() {
		return (com.top_logic.model.TLClass) tValueByName(EDGE_FORM_TYPE_ATTR);
	}

	/**
	 * Setter for part {@link #EDGE_FORM_TYPE_ATTR}.
	 */
	default void setEdgeFormType(com.top_logic.model.TLClass newValue) {
		tUpdateByName(EDGE_FORM_TYPE_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #EXPORT_DESCRIPTION_ATTR}.
	 */
	default com.top_logic.model.form.definition.FormDefinition getExportDescription() {
		return (com.top_logic.model.form.definition.FormDefinition) tValueByName(EXPORT_DESCRIPTION_ATTR);
	}

	/**
	 * Setter for part {@link #EXPORT_DESCRIPTION_ATTR}.
	 */
	default void setExportDescription(com.top_logic.model.form.definition.FormDefinition newValue) {
		tUpdateByName(EXPORT_DESCRIPTION_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #MODEL_TYPE_ATTR}.
	 */
	default com.top_logic.model.TLClass getModelType() {
		return (com.top_logic.model.TLClass) tValueByName(MODEL_TYPE_ATTR);
	}

	/**
	 * Setter for part {@link #MODEL_TYPE_ATTR}.
	 */
	default void setModelType(com.top_logic.model.TLClass newValue) {
		tUpdateByName(MODEL_TYPE_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #PROCESS_ATTR}.
	 */
	default com.top_logic.bpe.bpml.model.Process getProcess() {
		return (com.top_logic.bpe.bpml.model.Process) tValueByName(PROCESS_ATTR);
	}

	/**
	 * Setter for part {@link #PROCESS_ATTR}.
	 */
	default void setProcess(com.top_logic.bpe.bpml.model.Process newValue) {
		tUpdateByName(PROCESS_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #TASK_LABEL_ATTR}.
	 */
	default com.top_logic.model.search.expr.SearchExpression getTaskLabel() {
		return (com.top_logic.model.search.expr.SearchExpression) tValueByName(TASK_LABEL_ATTR);
	}

	/**
	 * Setter for part {@link #TASK_LABEL_ATTR}.
	 */
	default void setTaskLabel(com.top_logic.model.search.expr.SearchExpression newValue) {
		tUpdateByName(TASK_LABEL_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #TOKEN_TYPE_ATTR}.
	 */
	default com.top_logic.model.TLClass getTokenType() {
		return (com.top_logic.model.TLClass) tValueByName(TOKEN_TYPE_ATTR);
	}

	/**
	 * Setter for part {@link #TOKEN_TYPE_ATTR}.
	 */
	default void setTokenType(com.top_logic.model.TLClass newValue) {
		tUpdateByName(TOKEN_TYPE_ATTR, newValue);
	}

}
