/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.bpe.bpml.model.impl;

/**
 * Basic interface for {@link #START_EVENT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface StartEventBase extends com.top_logic.bpe.bpml.model.Event, com.top_logic.bpe.bpml.model.FlowTarget, com.top_logic.bpe.bpml.model.Iconified, com.top_logic.bpe.bpml.model.Described {

	/**
	 * Name of type <code>StartEvent</code>
	 */
	String START_EVENT_TYPE = "StartEvent";

	/**
	 * Part <code>title</code> of <code>StartEvent</code>
	 * 
	 * <p>
	 * Declared as <code>tl.model.i18n:I18NString</code> in configuration.
	 * </p>
	 */
	String TITLE_ATTR = "title";

	/**
	 * Getter for part {@link #TITLE_ATTR}.
	 */
	default com.top_logic.basic.util.ResKey getTitle() {
		return (com.top_logic.basic.util.ResKey) tValueByName(TITLE_ATTR);
	}

	/**
	 * Setter for part {@link #TITLE_ATTR}.
	 */
	default void setTitle(com.top_logic.basic.util.ResKey newValue) {
		tUpdateByName(TITLE_ATTR, newValue);
	}

}
