/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.demo.model.types.wrap;

/**
 * Basic interface for {@link #DEMO_TYPES_CONTAINER_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface DemoTypesContainerBase extends com.top_logic.demo.model.types.DemoTypesAll {

	/**
	 * Name of type <code>DemoTypesContainer</code>
	 */
	String DEMO_TYPES_CONTAINER_TYPE = "DemoTypesContainer";

	/**
	 * Getter for part {@link #CHILDREN_ATTR}.
	 */
	@Override
	@SuppressWarnings("unchecked")
	default java.util.List<? extends com.top_logic.demo.model.types.DemoTypesAll> getChildren() {
		return (java.util.List<? extends com.top_logic.demo.model.types.DemoTypesAll>) tValueByName(CHILDREN_ATTR);
	}

}
