/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.demo.model.types.wrap;

/**
 * Basic interface for {@link #DEMO_TYPES_ROOT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface DemoTypesRootBase extends com.top_logic.element.structured.StructuredElement {

	/**
	 * Name of type <code>DemoTypes.Root</code>
	 */
	String DEMO_TYPES_ROOT_TYPE = "DemoTypes.Root";

}
