/*
 * SPDX-FileCopyrightText: 2024 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.demo.model.types.wrap;

/**
 * Basic interface for {@link #ROOT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface RootBase extends com.top_logic.demo.model.types.DemoTypesRoot {

	/**
	 * Name of type <code>Root</code>
	 */
	String ROOT_TYPE = "Root";

	/**
	 * Part <code>name</code> of <code>Root</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Getter for part {@link #CHILDREN_ATTR}.
	 */
	@Override
	@SuppressWarnings("unchecked")
	default java.util.List<? extends com.top_logic.demo.model.types.RootChild> getChildren() {
		return (java.util.List<? extends com.top_logic.demo.model.types.RootChild>) tValueByName(CHILDREN_ATTR);
	}

}
