/*
 * SPDX-FileCopyrightText: 2012 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.basic.sql;

import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.util.logging.Logger;

import javax.sql.DataSource;


/**
 * Abstract proxy for {@link DataSource}.
 * 
 * @see #impl()
 * 
 * @author Automatically generated by <code>com.top_logic.basic.generate.ProxyGenerator</code>
 */
public abstract class DataSourceProxy implements DataSource{

	/**
	 * The underlying implementation.
	 */
	protected abstract DataSource impl();

	@Override
	public Connection getConnection() throws SQLException {
		return impl().getConnection();
	}

	@Override
	public Connection getConnection(String a1, String a2) throws SQLException {
		return impl().getConnection(a1, a2);
	}

	@Override
	public PrintWriter getLogWriter() throws SQLException {
		return impl().getLogWriter();
	}

	@Override
	public int getLoginTimeout() throws SQLException {
		return impl().getLoginTimeout();
	}

	@Override
	public void setLogWriter(PrintWriter a1) throws SQLException {
		impl().setLogWriter(a1);
	}

	@Override
	public void setLoginTimeout(int a1) throws SQLException {
		impl().setLoginTimeout(a1);
	}

	@Override
	public boolean isWrapperFor(Class<?> a1) throws SQLException {
		return impl().isWrapperFor(a1);
	}

	@Override
	public <T> T unwrap(Class<T> a1) throws SQLException {
		return impl().unwrap(a1);
	}

	@Override
	public Logger getParentLogger() throws SQLFeatureNotSupportedException {
		return impl().getParentLogger();
	}

}
