/*
 * SPDX-FileCopyrightText: 2026 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package test.com.top_logic.model.search.model.testScriptPathElement;

/**
 * Interface for {@link #NAMED_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceTemplateGenerator}
 */
public interface Named extends test.com.top_logic.model.search.model.testScriptPathElement.impl.NamedBase {

	// Wrapper functionality.

}
