#!/bin/bash

sed -i -e 's/{dbSchema}/[[tl.deb.dbSchema]]/g' [[tl.deb.installDir]]/bin/setup-db.sh
sed -i -e 's/{dbUser}/[[tl.deb.dbUser]]/g' [[tl.deb.installDir]]/bin/setup-db.sh

if [[ ! -e "/root/[[tl.deb.dbSchema]].db.passwd" ]]; then
	apg -m 16 -M NCL -q -n 1 > /root/[[tl.deb.dbSchema]].db.passwd

	[[tl.deb.installDir]]/bin/setup-db.sh
fi

sed -i -e 's/{dbDriver}/org.mariadb.jdbc.Driver/g' [[tl.deb.installDir]]/tomcat/context.xml
sed -i -e 's|{dbURL}|jdbc:mysql://localhost:3306/[[tl.deb.dbSchema]]|g' [[tl.deb.installDir]]/tomcat/context.xml
sed -i -e 's/{dbUser}/[[tl.deb.dbUser]]/g' [[tl.deb.installDir]]/tomcat/context.xml
sed -i -e 's/{contextName}/[[tl.deb.contextName]]/g' [[tl.deb.installDir]]/tomcat/context.xml
sed -i -e 's/{dbPasswd}/'$(cat /root/[[tl.deb.dbSchema]].db.passwd)'/g' [[tl.deb.installDir]]/tomcat/context.xml

sed -i -e 's/{contextName}/[[tl.deb.contextName]]/g' [[tl.deb.installDir]]/apache/site.conf
sed -i -e 's|{installDir}|[[tl.deb.installDir]]|g' [[tl.deb.installDir]]/apache/site.conf

service tomcat9 start

a2dissite 000-default.conf

a2enmod proxy_http
a2ensite "[[tl.deb.contextName]].conf"

systemctl restart apache2