/*
 * SPDX-FileCopyrightText: 2022 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.kafka.demo.model.types.impl;

import com.top_logic.knowledge.objects.KnowledgeObject;

/**
 * Wrapper implementation class for <code>kafka.demo:RemoteNode</code> business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.ImplementationTemplateGenerator}
 */
public class RemoteNodeImpl extends com.top_logic.element.meta.kbbased.AttributedWrapper implements com.top_logic.kafka.demo.model.types.RemoteNode {

	/**
	 * Default constructor.
	 */
	public RemoteNodeImpl(KnowledgeObject ko) {
		super(ko);
	}

}
