#!/bin/bash

# Container name and default for DB scheme and data folder.
APPNAME="toplogic"

# HTTP context name or "ROOT" for the root context ("/")
CONTEXT="ROOT"

# The http port where the app should be accessible
HTTP_PORT="8080"

# Absolute path to data folder or a simple name to specify a Docker volume. Default: Volume '[APPNAME]'
FILES=""

# Start the App locally.
START_LOCAL="false"

# Dry run. Only create docker configuration and exit.
CREATE_ONLY="false"

# Additional options passed to the Maven build process.
MVN_OPTS=""

##
## DB Parameters
##

# DB Options are: h2, mysql, mssql, postgre, oracle
DATABASE="h2"

# JDBC URL format dependent on the chosen database. Please refer to the specific documentations.
# Overrides hostname, port and scheme.
DB_URL=""

# [ip|hostname] Default: [IP of this machine] - H2 default:/var/lib/tomcat9/work/
DB_HOST=""

# Default: DB dependent default port
DB_PORT=""

# Default: [APPNAME] - In case of Oracle this is the prefixed (/)SERVICE or (:)SID name. 
# Example: :SIDNAME or /SERVICENAME. The Oracle Default will be an  service name: /[APPNAME]
DB_SCHEME=""

# Default: user
DB_USER=""

# Default: passwd
DB_PASSWD=""

##
## Environment parameters
##

# Minimum Java heap space to allocate for the application in mega bytes.
JAVA_XMS="256"

# Maximum Java heap space to allocate for the application.
# The container itself will take +20% of memory until a maximum overhead of 200MB
JAVA_XMX="4096"

# Specify how much of the available CPU resources (cores) a container can use. For instance, if the host machine has two
# CPUs and you set CPUS="1.5", the container is guaranteed at most one and a half CPU cores.
CPUS="2.0"

##
## Docker repository parameters
##

# Host name of the docker repository. 
DOCKER_REGISRTY="hub.docker.com"

# name of the docker images. Default: Same as [APPNAME]
DOCKER_IMAGE_NAME=""

# Tag for the docker image to push to the repository. 
DOCKER_TAG="latest"

# Enable the push to the configured Docker registry. 
DOCKER_PUSH="false"
