/*
 * SPDX-FileCopyrightText: 2017 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.model.search.persistency.expressions.impl;


import com.top_logic.knowledge.objects.KnowledgeObject;

/**
 * Implementation base class for wrapper classes of <code>SearchExpressionNode</code> business objects.
 * 
 * <p>
 * Note: this is generated code. Do not modify. Instead, create subclass and register this class as wrapper implementation.
 * </p>
 * 
 * @author Automatically generated by <code>com.top_logic.element.model.generate.ImplementationGenerator</code>
 */
public abstract class SearchExpressionNodeBaseImpl extends SearchExpressionBaseImpl implements com.top_logic.model.search.persistency.expressions.SearchExpressionNodeBase {

	/**
	 * Default constructor.
	 */
	public SearchExpressionNodeBaseImpl(KnowledgeObject ko) {
		super(ko);
	}

}
