/*
 * SPDX-FileCopyrightText: 2019 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.bpe.execution.model;

import java.util.Date;

import com.top_logic.bpe.bpml.model.ManualTask;
import com.top_logic.bpe.bpml.model.Task;
import com.top_logic.bpe.execution.model.impl.TokenBase;

/**
 * Interface for {@link #TOKEN_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceTemplateGenerator}
 */
public interface Token extends TokenBase {

	/**
	 * is the {@link Token} actual active?
	 */
	default boolean calculateActive() {
		ProcessExecution pe = getProcessExecution();
		if (pe == null) {
			return false;
		}
		return pe.getActiveTokens().contains(this);
	}

	/**
	 * only an active token can be user relevant
	 * 
	 * @return true iff is the token active an is the node of it a {@link Task}
	 */
	default boolean calculateUserRelevant() {
		return (getNode() instanceof ManualTask) && getActive();
	}

	/**
	 * duration of the token in minutes
	 */
	default long calculateDurationInMinutes() {
		Date created = tCreationDate();
		Date finished = getFinishDate();
		if (finished == null) {
			finished = new Date();
		}
		long duration = finished.getTime() - created.getTime();
		return duration / 1000 / 60;
	}

	/**
	 * String representation in log messages.
	 */
	default String debugString() {
		return getProcessExecution() + " in state " + getNode();
	}

}
